# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Position(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Position()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPosition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Position
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Position
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Position
    def Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def PositionStart(builder): builder.StartObject(2)
def Start(builder):
    return PositionStart(builder)
def PositionAddX(builder, x): builder.PrependFloat32Slot(0, x, 0.0)
def AddX(builder, x):
    return PositionAddX(builder, x)
def PositionAddZ(builder, z): builder.PrependFloat32Slot(1, z, 0.0)
def AddZ(builder, z):
    return PositionAddZ(builder, z)
def PositionEnd(builder): return builder.EndObject()
def End(builder):
    return PositionEnd(builder)