# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TranscendenceRecipeExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TranscendenceRecipeExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTranscendenceRecipeExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TranscendenceRecipeExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TranscendenceRecipeExcel
    def IdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TranscendenceRecipeExcel
    def DevNameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TranscendenceRecipeExcel
    def CostCurrencyTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TranscendenceRecipeExcel
    def CostCurrencyAmountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TranscendenceRecipeExcel
    def ParcelTypeField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # TranscendenceRecipeExcel
    def ParcelTypeFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # TranscendenceRecipeExcel
    def ParcelTypeFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TranscendenceRecipeExcel
    def ParcelTypeFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # TranscendenceRecipeExcel
    def ParcelIdField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # TranscendenceRecipeExcel
    def ParcelIdFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # TranscendenceRecipeExcel
    def ParcelIdFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TranscendenceRecipeExcel
    def ParcelIdFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # TranscendenceRecipeExcel
    def ParcelAmountField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # TranscendenceRecipeExcel
    def ParcelAmountFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # TranscendenceRecipeExcel
    def ParcelAmountFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TranscendenceRecipeExcel
    def ParcelAmountFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def TranscendenceRecipeExcelStart(builder): builder.StartObject(7)
def Start(builder):
    return TranscendenceRecipeExcelStart(builder)
def TranscendenceRecipeExcelAddIdField(builder, idField): builder.PrependInt32Slot(0, idField, 0)
def AddIdField(builder, idField):
    return TranscendenceRecipeExcelAddIdField(builder, idField)
def TranscendenceRecipeExcelAddDevNameField(builder, devNameField): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(devNameField), 0)
def AddDevNameField(builder, devNameField):
    return TranscendenceRecipeExcelAddDevNameField(builder, devNameField)
def TranscendenceRecipeExcelAddCostCurrencyTypeField(builder, costCurrencyTypeField): builder.PrependInt32Slot(2, costCurrencyTypeField, 0)
def AddCostCurrencyTypeField(builder, costCurrencyTypeField):
    return TranscendenceRecipeExcelAddCostCurrencyTypeField(builder, costCurrencyTypeField)
def TranscendenceRecipeExcelAddCostCurrencyAmountField(builder, costCurrencyAmountField): builder.PrependInt32Slot(3, costCurrencyAmountField, 0)
def AddCostCurrencyAmountField(builder, costCurrencyAmountField):
    return TranscendenceRecipeExcelAddCostCurrencyAmountField(builder, costCurrencyAmountField)
def TranscendenceRecipeExcelAddParcelTypeField(builder, parcelTypeField): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(parcelTypeField), 0)
def AddParcelTypeField(builder, parcelTypeField):
    return TranscendenceRecipeExcelAddParcelTypeField(builder, parcelTypeField)
def TranscendenceRecipeExcelStartParcelTypeFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartParcelTypeFieldVector(builder, numElems):
    return TranscendenceRecipeExcelStartParcelTypeFieldVector(builder, numElems)
def TranscendenceRecipeExcelAddParcelIdField(builder, parcelIdField): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(parcelIdField), 0)
def AddParcelIdField(builder, parcelIdField):
    return TranscendenceRecipeExcelAddParcelIdField(builder, parcelIdField)
def TranscendenceRecipeExcelStartParcelIdFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartParcelIdFieldVector(builder, numElems):
    return TranscendenceRecipeExcelStartParcelIdFieldVector(builder, numElems)
def TranscendenceRecipeExcelAddParcelAmountField(builder, parcelAmountField): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(parcelAmountField), 0)
def AddParcelAmountField(builder, parcelAmountField):
    return TranscendenceRecipeExcelAddParcelAmountField(builder, parcelAmountField)
def TranscendenceRecipeExcelStartParcelAmountFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartParcelAmountFieldVector(builder, numElems):
    return TranscendenceRecipeExcelStartParcelAmountFieldVector(builder, numElems)
def TranscendenceRecipeExcelEnd(builder): return builder.EndObject()
def End(builder):
    return TranscendenceRecipeExcelEnd(builder)