class DataHashException:
    GET_LOCAL_DATAHASH_STORE = 0
    SAVE_LOCAL_DATAHASH = 1
    SAVE_LOADL_DATAHASH_DICTIONARY = 2
    GET_LOCAL_DATAHASH = 3
    DELETE_LOCAL_DATAHASH = 4
    DELETE_LOCAL_DATAHASH_BY_LIST = 5
    DELETE_ALL_LOCAL_DATAHASH = 6
    GET_ALL_LOCAL_DATAHASH_PATTERN = 7
