class ErrorCode:
    PROCESS_TIMEOUT = 0
    APPLICATION_SUSPEND = 1
    HTTP_CLIENT_ERROR = 2
    HTTP_SERVER_ERROR = 3
    NETWORK_ERROR = 4
    FILESYSTEM_ERROR = 5
    APPLICATION_ERROR = 6
    CONSISTENCY_ERROR = 7
