class GlyphLoadFlags:
    LOAD_DEFAULT = 0
    LOAD_NO_SCALE = 1
    LOAD_NO_HINTING = 2
    LOAD_RENDER = 3
    LOAD_NO_BITMAP = 4
    LOAD_FORCE_AUTOHINT = 5
    LOAD_MONOCHROME = 6
    LOAD_NO_AUTOHINT = 7
    LOAD_COLOR = 8
    LOAD_COMPUTE_METRICS = 9
    LOAD_BITMAP_METRICS_ONLY = 10
