# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LocalizeGachaShopExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LocalizeGachaShopExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLocalizeGachaShopExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LocalizeGachaShopExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LocalizeGachaShopExcel
    def GachaShopId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # LocalizeGachaShopExcel
    def TabNameKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeGachaShopExcel
    def TabNameJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeGachaShopExcel
    def TitleNameKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeGachaShopExcel
    def TitleNameJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeGachaShopExcel
    def SubTitleKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeGachaShopExcel
    def SubTitleJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeGachaShopExcel
    def GachaDescriptionKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeGachaShopExcel
    def GachaDescriptionJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeGachaShopExcel
    def GachaPeriodCN(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def LocalizeGachaShopExcelStart(builder): builder.StartObject(10)
def Start(builder):
    return LocalizeGachaShopExcelStart(builder)
def LocalizeGachaShopExcelAddGachaShopId(builder, gachaShopId): builder.PrependInt32Slot(0, gachaShopId, 0)
def AddGachaShopId(builder, gachaShopId):
    return LocalizeGachaShopExcelAddGachaShopId(builder, gachaShopId)
def LocalizeGachaShopExcelAddTabNameKr(builder, tabNameKr): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(tabNameKr), 0)
def AddTabNameKr(builder, tabNameKr):
    return LocalizeGachaShopExcelAddTabNameKr(builder, tabNameKr)
def LocalizeGachaShopExcelAddTabNameJp(builder, tabNameJp): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(tabNameJp), 0)
def AddTabNameJp(builder, tabNameJp):
    return LocalizeGachaShopExcelAddTabNameJp(builder, tabNameJp)
def LocalizeGachaShopExcelAddTitleNameKr(builder, titleNameKr): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(titleNameKr), 0)
def AddTitleNameKr(builder, titleNameKr):
    return LocalizeGachaShopExcelAddTitleNameKr(builder, titleNameKr)
def LocalizeGachaShopExcelAddTitleNameJp(builder, titleNameJp): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(titleNameJp), 0)
def AddTitleNameJp(builder, titleNameJp):
    return LocalizeGachaShopExcelAddTitleNameJp(builder, titleNameJp)
def LocalizeGachaShopExcelAddSubTitleKr(builder, subTitleKr): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(subTitleKr), 0)
def AddSubTitleKr(builder, subTitleKr):
    return LocalizeGachaShopExcelAddSubTitleKr(builder, subTitleKr)
def LocalizeGachaShopExcelAddSubTitleJp(builder, subTitleJp): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(subTitleJp), 0)
def AddSubTitleJp(builder, subTitleJp):
    return LocalizeGachaShopExcelAddSubTitleJp(builder, subTitleJp)
def LocalizeGachaShopExcelAddGachaDescriptionKr(builder, gachaDescriptionKr): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(gachaDescriptionKr), 0)
def AddGachaDescriptionKr(builder, gachaDescriptionKr):
    return LocalizeGachaShopExcelAddGachaDescriptionKr(builder, gachaDescriptionKr)
def LocalizeGachaShopExcelAddGachaDescriptionJp(builder, gachaDescriptionJp): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(gachaDescriptionJp), 0)
def AddGachaDescriptionJp(builder, gachaDescriptionJp):
    return LocalizeGachaShopExcelAddGachaDescriptionJp(builder, gachaDescriptionJp)
def LocalizeGachaShopExcelAddGachaPeriodCN(builder, gachaPeriodCN): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(gachaPeriodCN), 0)
def AddGachaPeriodCN(builder, gachaPeriodCN):
    return LocalizeGachaShopExcelAddGachaPeriodCN(builder, gachaPeriodCN)
def LocalizeGachaShopExcelEnd(builder): return builder.EndObject()
def End(builder):
    return LocalizeGachaShopExcelEnd(builder)