class LogResult:
    OK = 0
    INVALID = 1
    WRITE_ERROR = 2
    DROP_ERROR = 3
    NETWORK_ERROR = 4
    QUOTA_ERROR = 5
    UNAUTHORIZED = 6
    SERVER_ERROR = 7
    DISCARD_ERROR = 8
    TIME_ERROR = 9
    EXIT_BUFFERED = 10
