# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MinigameJankenFixedEchelonSetExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MinigameJankenFixedEchelonSetExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMinigameJankenFixedEchelonSetExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MinigameJankenFixedEchelonSetExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MinigameJankenFixedEchelonSetExcel
    def FixedEchelonID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameJankenFixedEchelonSetExcel
    def EchelonSceneSkip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MinigameJankenFixedEchelonSetExcel
    def CharacterID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameJankenFixedEchelonSetExcel
    def EquipMentID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def MinigameJankenFixedEchelonSetExcelStart(builder): builder.StartObject(4)
def Start(builder):
    return MinigameJankenFixedEchelonSetExcelStart(builder)
def MinigameJankenFixedEchelonSetExcelAddFixedEchelonID(builder, fixedEchelonID): builder.PrependInt32Slot(0, fixedEchelonID, 0)
def AddFixedEchelonID(builder, fixedEchelonID):
    return MinigameJankenFixedEchelonSetExcelAddFixedEchelonID(builder, fixedEchelonID)
def MinigameJankenFixedEchelonSetExcelAddEchelonSceneSkip(builder, echelonSceneSkip): builder.PrependBoolSlot(1, echelonSceneSkip, 0)
def AddEchelonSceneSkip(builder, echelonSceneSkip):
    return MinigameJankenFixedEchelonSetExcelAddEchelonSceneSkip(builder, echelonSceneSkip)
def MinigameJankenFixedEchelonSetExcelAddCharacterID(builder, characterID): builder.PrependInt32Slot(2, characterID, 0)
def AddCharacterID(builder, characterID):
    return MinigameJankenFixedEchelonSetExcelAddCharacterID(builder, characterID)
def MinigameJankenFixedEchelonSetExcelAddEquipMentID(builder, equipMentID): builder.PrependInt32Slot(3, equipMentID, 0)
def AddEquipMentID(builder, equipMentID):
    return MinigameJankenFixedEchelonSetExcelAddEquipMentID(builder, equipMentID)
def MinigameJankenFixedEchelonSetExcelEnd(builder): return builder.EndObject()
def End(builder):
    return MinigameJankenFixedEchelonSetExcelEnd(builder)