# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MultiFloorRaidRewardExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MultiFloorRaidRewardExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMultiFloorRaidRewardExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MultiFloorRaidRewardExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MultiFloorRaidRewardExcel
    def RewardGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MultiFloorRaidRewardExcel
    def ClearStageRewardProb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MultiFloorRaidRewardExcel
    def ClearStageRewardParcelType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MultiFloorRaidRewardExcel
    def ClearStageRewardParcelUniqueID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MultiFloorRaidRewardExcel
    def ClearStageRewardAmount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def MultiFloorRaidRewardExcelStart(builder): builder.StartObject(5)
def Start(builder):
    return MultiFloorRaidRewardExcelStart(builder)
def MultiFloorRaidRewardExcelAddRewardGroupId(builder, rewardGroupId): builder.PrependInt32Slot(0, rewardGroupId, 0)
def AddRewardGroupId(builder, rewardGroupId):
    return MultiFloorRaidRewardExcelAddRewardGroupId(builder, rewardGroupId)
def MultiFloorRaidRewardExcelAddClearStageRewardProb(builder, clearStageRewardProb): builder.PrependInt32Slot(1, clearStageRewardProb, 0)
def AddClearStageRewardProb(builder, clearStageRewardProb):
    return MultiFloorRaidRewardExcelAddClearStageRewardProb(builder, clearStageRewardProb)
def MultiFloorRaidRewardExcelAddClearStageRewardParcelType(builder, clearStageRewardParcelType): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(clearStageRewardParcelType), 0)
def AddClearStageRewardParcelType(builder, clearStageRewardParcelType):
    return MultiFloorRaidRewardExcelAddClearStageRewardParcelType(builder, clearStageRewardParcelType)
def MultiFloorRaidRewardExcelAddClearStageRewardParcelUniqueID(builder, clearStageRewardParcelUniqueID): builder.PrependInt32Slot(3, clearStageRewardParcelUniqueID, 0)
def AddClearStageRewardParcelUniqueID(builder, clearStageRewardParcelUniqueID):
    return MultiFloorRaidRewardExcelAddClearStageRewardParcelUniqueID(builder, clearStageRewardParcelUniqueID)
def MultiFloorRaidRewardExcelAddClearStageRewardAmount(builder, clearStageRewardAmount): builder.PrependInt32Slot(4, clearStageRewardAmount, 0)
def AddClearStageRewardAmount(builder, clearStageRewardAmount):
    return MultiFloorRaidRewardExcelAddClearStageRewardAmount(builder, clearStageRewardAmount)
def MultiFloorRaidRewardExcelEnd(builder): return builder.EndObject()
def End(builder):
    return MultiFloorRaidRewardExcelEnd(builder)