class NativeErrorCode:
    ERROR_INVALID_FILEPATH_PARAMETER = 0
    ERROR_CANNOT_OPEN_FILE_FOR_WRITE = 1
    ERROR_CANNOT_OPEN_FILE_FOR_READ = 2
    ERROR_INPUT_FILESTREAM_IS_NOT_OGG_STREAM = 3
    ERROR_READING_OGG_STREAM = 4
    ERROR_INVALID_SAMPLES_PARAMETER = 5
    ERROR_INVALID_SAMPLESLENGTH_PARAMETER = 6
    ERROR_INVALID_CHANNELS_PARAMETER = 7
    ERROR_INVALID_FREQUENCY_PARAMETER = 8
    ERROR_INVALID_BASE_QUALITY_PARAMETER = 9
    ERROR_MALLOC_RETURNED_NULL = 10
    ERROR_BYTES_MEMORY_ARRAY_NULL = 11
    ERROR_INVALID_WRITE_CALLBACK_PARAMETER = 12
