class NXToyPromotionBannerButtonType:
    META_PURCHASED = 0
    META = 1
    URL = 2
    CLOSE_BUTTON = 3
    DO_NOT_SHOW_TODAY = 4
    URL_SCHEME_PURCHASED = 5
    URL_SCHEME = 6
    COMMUNITY = 7
    SURVEY = 8
    URL_BROWSER = 9
    DO_NOT_SHOW_ANYMORE = 10
    BYPASS_AUTH_URL = 11
    DO_NOT_SHOW_7DAYS = 12
