class SessionState:
    NONE = 0
    WAITING_SERVER_RESPONSE = 1
    RECEIVED_SERVER_RESPONSE = 2
    FILE_NOT_FOUND = 3
    FAILED = 4
    SUCCESS = 5
    CLIENT_NETWORK_NOT_REACHABLE = 6
    SERVER_RESPONSE_ERROR = 7
    SERVER_NOT_RESPONSE = 8
