# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShopFreeRecruitPeriodExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShopFreeRecruitPeriodExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShopFreeRecruitPeriodExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ShopFreeRecruitPeriodExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShopFreeRecruitPeriodExcel
    def ShopFreeRecruitId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopFreeRecruitPeriodExcel
    def ShopFreeRecruitIntervalId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopFreeRecruitPeriodExcel
    def IntervalDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopFreeRecruitPeriodExcel
    def FreeRecruitCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ShopFreeRecruitPeriodExcelStart(builder): builder.StartObject(4)
def Start(builder):
    return ShopFreeRecruitPeriodExcelStart(builder)
def ShopFreeRecruitPeriodExcelAddShopFreeRecruitId(builder, shopFreeRecruitId): builder.PrependInt32Slot(0, shopFreeRecruitId, 0)
def AddShopFreeRecruitId(builder, shopFreeRecruitId):
    return ShopFreeRecruitPeriodExcelAddShopFreeRecruitId(builder, shopFreeRecruitId)
def ShopFreeRecruitPeriodExcelAddShopFreeRecruitIntervalId(builder, shopFreeRecruitIntervalId): builder.PrependInt32Slot(1, shopFreeRecruitIntervalId, 0)
def AddShopFreeRecruitIntervalId(builder, shopFreeRecruitIntervalId):
    return ShopFreeRecruitPeriodExcelAddShopFreeRecruitIntervalId(builder, shopFreeRecruitIntervalId)
def ShopFreeRecruitPeriodExcelAddIntervalDate(builder, intervalDate): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(intervalDate), 0)
def AddIntervalDate(builder, intervalDate):
    return ShopFreeRecruitPeriodExcelAddIntervalDate(builder, intervalDate)
def ShopFreeRecruitPeriodExcelAddFreeRecruitCount(builder, freeRecruitCount): builder.PrependInt32Slot(3, freeRecruitCount, 0)
def AddFreeRecruitCount(builder, freeRecruitCount):
    return ShopFreeRecruitPeriodExcelAddFreeRecruitCount(builder, freeRecruitCount)
def ShopFreeRecruitPeriodExcelEnd(builder): return builder.EndObject()
def End(builder):
    return ShopFreeRecruitPeriodExcelEnd(builder)