# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShopFreeRecruitExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShopFreeRecruitExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShopFreeRecruitExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ShopFreeRecruitExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShopFreeRecruitExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ShopFreeRecruitExcel
    def FreeRecruitPeriodFrom(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopFreeRecruitExcel
    def FreeRecruitPeriodTo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopFreeRecruitExcel
    def FreeRecruitType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopFreeRecruitExcel
    def FreeRecruitDecorationImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ShopFreeRecruitExcel
    def TenRecruitCountOnly(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ShopFreeRecruitExcel
    def ShopRecruitId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ShopFreeRecruitExcel
    def ShopRecruitIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # ShopFreeRecruitExcel
    def ShopRecruitIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ShopFreeRecruitExcel
    def ShopRecruitIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def ShopFreeRecruitExcelStart(builder): builder.StartObject(7)
def Start(builder):
    return ShopFreeRecruitExcelStart(builder)
def ShopFreeRecruitExcelAddId(builder, id): builder.PrependInt32Slot(0, id, 0)
def AddId(builder, id):
    return ShopFreeRecruitExcelAddId(builder, id)
def ShopFreeRecruitExcelAddFreeRecruitPeriodFrom(builder, freeRecruitPeriodFrom): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(freeRecruitPeriodFrom), 0)
def AddFreeRecruitPeriodFrom(builder, freeRecruitPeriodFrom):
    return ShopFreeRecruitExcelAddFreeRecruitPeriodFrom(builder, freeRecruitPeriodFrom)
def ShopFreeRecruitExcelAddFreeRecruitPeriodTo(builder, freeRecruitPeriodTo): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(freeRecruitPeriodTo), 0)
def AddFreeRecruitPeriodTo(builder, freeRecruitPeriodTo):
    return ShopFreeRecruitExcelAddFreeRecruitPeriodTo(builder, freeRecruitPeriodTo)
def ShopFreeRecruitExcelAddFreeRecruitType(builder, freeRecruitType): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(freeRecruitType), 0)
def AddFreeRecruitType(builder, freeRecruitType):
    return ShopFreeRecruitExcelAddFreeRecruitType(builder, freeRecruitType)
def ShopFreeRecruitExcelAddFreeRecruitDecorationImagePath(builder, freeRecruitDecorationImagePath): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(freeRecruitDecorationImagePath), 0)
def AddFreeRecruitDecorationImagePath(builder, freeRecruitDecorationImagePath):
    return ShopFreeRecruitExcelAddFreeRecruitDecorationImagePath(builder, freeRecruitDecorationImagePath)
def ShopFreeRecruitExcelAddTenRecruitCountOnly(builder, tenRecruitCountOnly): builder.PrependBoolSlot(5, tenRecruitCountOnly, 0)
def AddTenRecruitCountOnly(builder, tenRecruitCountOnly):
    return ShopFreeRecruitExcelAddTenRecruitCountOnly(builder, tenRecruitCountOnly)
def ShopFreeRecruitExcelAddShopRecruitId(builder, shopRecruitId): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(shopRecruitId), 0)
def AddShopRecruitId(builder, shopRecruitId):
    return ShopFreeRecruitExcelAddShopRecruitId(builder, shopRecruitId)
def ShopFreeRecruitExcelStartShopRecruitIdVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartShopRecruitIdVector(builder, numElems):
    return ShopFreeRecruitExcelStartShopRecruitIdVector(builder, numElems)
def ShopFreeRecruitExcelEnd(builder): return builder.EndObject()
def End(builder):
    return ShopFreeRecruitExcelEnd(builder)