class unitytls_error_code:
    UNITYTLS_SUCCESS = 0
    UNITYTLS_INVALID_ARGUMENT = 1
    UNITYTLS_INVALID_FORMAT = 2
    UNITYTLS_INVALID_PASSWORD = 3
    UNITYTLS_INVALID_STATE = 4
    UNITYTLS_BUFFER_OVERFLOW = 5
    UNITYTLS_OUT_OF_MEMORY = 6
    UNITYTLS_INTERNAL_ERROR = 7
    UNITYTLS_NOT_SUPPORTED = 8
    UNITYTLS_ENTROPY_SOURCE_FAILED = 9
    UNITYTLS_STREAM_CLOSED = 10
    UNITYTLS_USER_CUSTOM_ERROR_START = 11
    UNITYTLS_USER_WOULD_BLOCK = 12
    UNITYTLS_USER_READ_FAILED = 13
    UNITYTLS_USER_WRITE_FAILED = 14
    UNITYTLS_USER_UNKNOWN_ERROR = 15
    UNITYTLS_USER_CUSTOM_ERROR_END = 16
