# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VoiceTimelineExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VoiceTimelineExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVoiceTimelineExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VoiceTimelineExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VoiceTimelineExcel
    def UniqueId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VoiceTimelineExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # VoiceTimelineExcel
    def Nation(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # VoiceTimelineExcel
    def NationAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # VoiceTimelineExcel
    def NationLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VoiceTimelineExcel
    def NationIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # VoiceTimelineExcel
    def Path(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # VoiceTimelineExcel
    def PathLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VoiceTimelineExcel
    def PathIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # VoiceTimelineExcel
    def SoundVolume(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # VoiceTimelineExcel
    def SoundVolumeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # VoiceTimelineExcel
    def SoundVolumeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VoiceTimelineExcel
    def SoundVolumeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def VoiceTimelineExcelStart(builder): builder.StartObject(5)
def Start(builder):
    return VoiceTimelineExcelStart(builder)
def VoiceTimelineExcelAddUniqueId(builder, uniqueId): builder.PrependInt32Slot(0, uniqueId, 0)
def AddUniqueId(builder, uniqueId):
    return VoiceTimelineExcelAddUniqueId(builder, uniqueId)
def VoiceTimelineExcelAddId(builder, id): builder.PrependUint32Slot(1, id, 0)
def AddId(builder, id):
    return VoiceTimelineExcelAddId(builder, id)
def VoiceTimelineExcelAddNation(builder, nation): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(nation), 0)
def AddNation(builder, nation):
    return VoiceTimelineExcelAddNation(builder, nation)
def VoiceTimelineExcelStartNationVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartNationVector(builder, numElems):
    return VoiceTimelineExcelStartNationVector(builder, numElems)
def VoiceTimelineExcelAddPath(builder, path): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(path), 0)
def AddPath(builder, path):
    return VoiceTimelineExcelAddPath(builder, path)
def VoiceTimelineExcelStartPathVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartPathVector(builder, numElems):
    return VoiceTimelineExcelStartPathVector(builder, numElems)
def VoiceTimelineExcelAddSoundVolume(builder, soundVolume): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(soundVolume), 0)
def AddSoundVolume(builder, soundVolume):
    return VoiceTimelineExcelAddSoundVolume(builder, soundVolume)
def VoiceTimelineExcelStartSoundVolumeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartSoundVolumeVector(builder, numElems):
    return VoiceTimelineExcelStartSoundVolumeVector(builder, numElems)
def VoiceTimelineExcelEnd(builder): return builder.EndObject()
def End(builder):
    return VoiceTimelineExcelEnd(builder)