# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AcademyMessangerExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AcademyMessangerExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAcademyMessangerExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AcademyMessangerExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AcademyMessangerExcel
    def MessageGroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AcademyMessangerExcel
    def IdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AcademyMessangerExcel
    def CharacterIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AcademyMessangerExcel
    def MessageConditionField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AcademyMessangerExcel
    def ConditionValueField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AcademyMessangerExcel
    def PreConditionGroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AcademyMessangerExcel
    def PreConditionFavorScheduleIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AcademyMessangerExcel
    def FavorScheduleIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AcademyMessangerExcel
    def NextGroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AcademyMessangerExcel
    def FeedbackTimeMillisecField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AcademyMessangerExcel
    def MessageTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AcademyMessangerExcel
    def ImagePathField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AcademyMessangerExcel
    def MessageKRField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AcademyMessangerExcel
    def MessageJPField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def AcademyMessangerExcelStart(builder): builder.StartObject(14)
def Start(builder):
    return AcademyMessangerExcelStart(builder)
def AcademyMessangerExcelAddMessageGroupIdField(builder, messageGroupIdField): builder.PrependInt32Slot(0, messageGroupIdField, 0)
def AddMessageGroupIdField(builder, messageGroupIdField):
    return AcademyMessangerExcelAddMessageGroupIdField(builder, messageGroupIdField)
def AcademyMessangerExcelAddIdField(builder, idField): builder.PrependInt32Slot(1, idField, 0)
def AddIdField(builder, idField):
    return AcademyMessangerExcelAddIdField(builder, idField)
def AcademyMessangerExcelAddCharacterIdField(builder, characterIdField): builder.PrependInt32Slot(2, characterIdField, 0)
def AddCharacterIdField(builder, characterIdField):
    return AcademyMessangerExcelAddCharacterIdField(builder, characterIdField)
def AcademyMessangerExcelAddMessageConditionField(builder, messageConditionField): builder.PrependInt32Slot(3, messageConditionField, 0)
def AddMessageConditionField(builder, messageConditionField):
    return AcademyMessangerExcelAddMessageConditionField(builder, messageConditionField)
def AcademyMessangerExcelAddConditionValueField(builder, conditionValueField): builder.PrependInt32Slot(4, conditionValueField, 0)
def AddConditionValueField(builder, conditionValueField):
    return AcademyMessangerExcelAddConditionValueField(builder, conditionValueField)
def AcademyMessangerExcelAddPreConditionGroupIdField(builder, preConditionGroupIdField): builder.PrependInt32Slot(5, preConditionGroupIdField, 0)
def AddPreConditionGroupIdField(builder, preConditionGroupIdField):
    return AcademyMessangerExcelAddPreConditionGroupIdField(builder, preConditionGroupIdField)
def AcademyMessangerExcelAddPreConditionFavorScheduleIdField(builder, preConditionFavorScheduleIdField): builder.PrependInt32Slot(6, preConditionFavorScheduleIdField, 0)
def AddPreConditionFavorScheduleIdField(builder, preConditionFavorScheduleIdField):
    return AcademyMessangerExcelAddPreConditionFavorScheduleIdField(builder, preConditionFavorScheduleIdField)
def AcademyMessangerExcelAddFavorScheduleIdField(builder, favorScheduleIdField): builder.PrependInt32Slot(7, favorScheduleIdField, 0)
def AddFavorScheduleIdField(builder, favorScheduleIdField):
    return AcademyMessangerExcelAddFavorScheduleIdField(builder, favorScheduleIdField)
def AcademyMessangerExcelAddNextGroupIdField(builder, nextGroupIdField): builder.PrependInt32Slot(8, nextGroupIdField, 0)
def AddNextGroupIdField(builder, nextGroupIdField):
    return AcademyMessangerExcelAddNextGroupIdField(builder, nextGroupIdField)
def AcademyMessangerExcelAddFeedbackTimeMillisecField(builder, feedbackTimeMillisecField): builder.PrependInt32Slot(9, feedbackTimeMillisecField, 0)
def AddFeedbackTimeMillisecField(builder, feedbackTimeMillisecField):
    return AcademyMessangerExcelAddFeedbackTimeMillisecField(builder, feedbackTimeMillisecField)
def AcademyMessangerExcelAddMessageTypeField(builder, messageTypeField): builder.PrependInt32Slot(10, messageTypeField, 0)
def AddMessageTypeField(builder, messageTypeField):
    return AcademyMessangerExcelAddMessageTypeField(builder, messageTypeField)
def AcademyMessangerExcelAddImagePathField(builder, imagePathField): builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(imagePathField), 0)
def AddImagePathField(builder, imagePathField):
    return AcademyMessangerExcelAddImagePathField(builder, imagePathField)
def AcademyMessangerExcelAddMessageKRField(builder, messageKRField): builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(messageKRField), 0)
def AddMessageKRField(builder, messageKRField):
    return AcademyMessangerExcelAddMessageKRField(builder, messageKRField)
def AcademyMessangerExcelAddMessageJPField(builder, messageJPField): builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(messageJPField), 0)
def AddMessageJPField(builder, messageJPField):
    return AcademyMessangerExcelAddMessageJPField(builder, messageJPField)
def AcademyMessangerExcelEnd(builder): return builder.EndObject()
def End(builder):
    return AcademyMessangerExcelEnd(builder)