# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ArenaLevelSectionExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ArenaLevelSectionExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsArenaLevelSectionExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ArenaLevelSectionExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ArenaLevelSectionExcel
    def ArenaSeasonIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArenaLevelSectionExcel
    def StartLevelField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArenaLevelSectionExcel
    def LastLevelField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ArenaLevelSectionExcel
    def UserCountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ArenaLevelSectionExcelStart(builder): builder.StartObject(4)
def Start(builder):
    return ArenaLevelSectionExcelStart(builder)
def ArenaLevelSectionExcelAddArenaSeasonIdField(builder, arenaSeasonIdField): builder.PrependInt32Slot(0, arenaSeasonIdField, 0)
def AddArenaSeasonIdField(builder, arenaSeasonIdField):
    return ArenaLevelSectionExcelAddArenaSeasonIdField(builder, arenaSeasonIdField)
def ArenaLevelSectionExcelAddStartLevelField(builder, startLevelField): builder.PrependInt32Slot(1, startLevelField, 0)
def AddStartLevelField(builder, startLevelField):
    return ArenaLevelSectionExcelAddStartLevelField(builder, startLevelField)
def ArenaLevelSectionExcelAddLastLevelField(builder, lastLevelField): builder.PrependInt32Slot(2, lastLevelField, 0)
def AddLastLevelField(builder, lastLevelField):
    return ArenaLevelSectionExcelAddLastLevelField(builder, lastLevelField)
def ArenaLevelSectionExcelAddUserCountField(builder, userCountField): builder.PrependInt32Slot(3, userCountField, 0)
def AddUserCountField(builder, userCountField):
    return ArenaLevelSectionExcelAddUserCountField(builder, userCountField)
def ArenaLevelSectionExcelEnd(builder): return builder.EndObject()
def End(builder):
    return ArenaLevelSectionExcelEnd(builder)