# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CharacterExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CharacterExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCharacterExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CharacterExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CharacterExcel
    def IdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def DevNameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterExcel
    def CostumeGroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def IsPlayableField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def ProductionStepField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def CollectionVisibleField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def ReleaseDateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterExcel
    def CollectionVisibleStartDateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterExcel
    def CollectionVisibleEndDateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterExcel
    def IsPlayableCharacterField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def LocalizeEtcIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def RarityField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def IsNPCField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def TacticEntityTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def CanSurviveField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def IsDummyField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def SubPartsCountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def TacticRoleField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CharacterExcel
    def WeaponTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def TacticRangeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def BulletTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def ArmorTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def AimIKTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def SchoolField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def ClubField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def DefaultStarGradeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def MaxStarGradeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def StatLevelUpTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def SquadTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def JumpableField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def PersonalityIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def CharacterAIIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def ExternalBTIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def MainCombatStyleIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def CombatStyleIndexField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def UseRepStyleOnCharacterGrowthField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def ScenarioCharacterField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterExcel
    def SpawnTemplateIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def FavorLevelupTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(80))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def EquipmentSlotField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(82))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # CharacterExcel
    def EquipmentSlotFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(82))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # CharacterExcel
    def EquipmentSlotFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(82))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CharacterExcel
    def EquipmentSlotFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(82))
        return o == 0

    # CharacterExcel
    def WeaponLocalizeIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(84))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def DisplayEnemyInfoField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(86))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def BodyRadiusField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(88))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def RandomEffectRadiusField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(90))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def TargetGuideScaleField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(92))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CharacterExcel
    def HPBarHideField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(94))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def HpBarHeightField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(96))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CharacterExcel
    def HighlightFloaterHeightField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(98))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CharacterExcel
    def EmojiOffsetXField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(100))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CharacterExcel
    def EmojiOffsetYField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(102))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # CharacterExcel
    def MoveStartFrameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(104))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def MoveEndFrameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(106))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def JumpMotionFrameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(108))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def AppearFrameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(110))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def CanMoveField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(112))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def CanFixField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(114))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def CanCrowdControlField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(116))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def CanBattleItemMoveField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(118))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def IgnoreObstacleField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(120))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def IsAirUnitField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(122))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterExcel
    def AirUnitHeightField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(124))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def TagsField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(126))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # CharacterExcel
    def TagsFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(126))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # CharacterExcel
    def TagsFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(126))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CharacterExcel
    def TagsFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(126))
        return o == 0

    # CharacterExcel
    def SecretStoneItemIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(128))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def SecretStoneItemAmountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(130))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def CharacterPieceItemIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(132))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def CharacterPieceItemAmountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(134))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterExcel
    def CombineRecipeIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(136))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def CharacterExcelStart(builder): builder.StartObject(67)
def Start(builder):
    return CharacterExcelStart(builder)
def CharacterExcelAddIdField(builder, idField): builder.PrependInt32Slot(0, idField, 0)
def AddIdField(builder, idField):
    return CharacterExcelAddIdField(builder, idField)
def CharacterExcelAddDevNameField(builder, devNameField): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(devNameField), 0)
def AddDevNameField(builder, devNameField):
    return CharacterExcelAddDevNameField(builder, devNameField)
def CharacterExcelAddCostumeGroupIdField(builder, costumeGroupIdField): builder.PrependInt32Slot(2, costumeGroupIdField, 0)
def AddCostumeGroupIdField(builder, costumeGroupIdField):
    return CharacterExcelAddCostumeGroupIdField(builder, costumeGroupIdField)
def CharacterExcelAddIsPlayableField(builder, isPlayableField): builder.PrependBoolSlot(3, isPlayableField, 0)
def AddIsPlayableField(builder, isPlayableField):
    return CharacterExcelAddIsPlayableField(builder, isPlayableField)
def CharacterExcelAddProductionStepField(builder, productionStepField): builder.PrependInt32Slot(4, productionStepField, 0)
def AddProductionStepField(builder, productionStepField):
    return CharacterExcelAddProductionStepField(builder, productionStepField)
def CharacterExcelAddCollectionVisibleField(builder, collectionVisibleField): builder.PrependBoolSlot(5, collectionVisibleField, 0)
def AddCollectionVisibleField(builder, collectionVisibleField):
    return CharacterExcelAddCollectionVisibleField(builder, collectionVisibleField)
def CharacterExcelAddReleaseDateField(builder, releaseDateField): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(releaseDateField), 0)
def AddReleaseDateField(builder, releaseDateField):
    return CharacterExcelAddReleaseDateField(builder, releaseDateField)
def CharacterExcelAddCollectionVisibleStartDateField(builder, collectionVisibleStartDateField): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(collectionVisibleStartDateField), 0)
def AddCollectionVisibleStartDateField(builder, collectionVisibleStartDateField):
    return CharacterExcelAddCollectionVisibleStartDateField(builder, collectionVisibleStartDateField)
def CharacterExcelAddCollectionVisibleEndDateField(builder, collectionVisibleEndDateField): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(collectionVisibleEndDateField), 0)
def AddCollectionVisibleEndDateField(builder, collectionVisibleEndDateField):
    return CharacterExcelAddCollectionVisibleEndDateField(builder, collectionVisibleEndDateField)
def CharacterExcelAddIsPlayableCharacterField(builder, isPlayableCharacterField): builder.PrependBoolSlot(9, isPlayableCharacterField, 0)
def AddIsPlayableCharacterField(builder, isPlayableCharacterField):
    return CharacterExcelAddIsPlayableCharacterField(builder, isPlayableCharacterField)
def CharacterExcelAddLocalizeEtcIdField(builder, localizeEtcIdField): builder.PrependUint32Slot(10, localizeEtcIdField, 0)
def AddLocalizeEtcIdField(builder, localizeEtcIdField):
    return CharacterExcelAddLocalizeEtcIdField(builder, localizeEtcIdField)
def CharacterExcelAddRarityField(builder, rarityField): builder.PrependInt32Slot(11, rarityField, 0)
def AddRarityField(builder, rarityField):
    return CharacterExcelAddRarityField(builder, rarityField)
def CharacterExcelAddIsNPCField(builder, isNPCField): builder.PrependBoolSlot(12, isNPCField, 0)
def AddIsNPCField(builder, isNPCField):
    return CharacterExcelAddIsNPCField(builder, isNPCField)
def CharacterExcelAddTacticEntityTypeField(builder, tacticEntityTypeField): builder.PrependInt32Slot(13, tacticEntityTypeField, 0)
def AddTacticEntityTypeField(builder, tacticEntityTypeField):
    return CharacterExcelAddTacticEntityTypeField(builder, tacticEntityTypeField)
def CharacterExcelAddCanSurviveField(builder, canSurviveField): builder.PrependBoolSlot(14, canSurviveField, 0)
def AddCanSurviveField(builder, canSurviveField):
    return CharacterExcelAddCanSurviveField(builder, canSurviveField)
def CharacterExcelAddIsDummyField(builder, isDummyField): builder.PrependBoolSlot(15, isDummyField, 0)
def AddIsDummyField(builder, isDummyField):
    return CharacterExcelAddIsDummyField(builder, isDummyField)
def CharacterExcelAddSubPartsCountField(builder, subPartsCountField): builder.PrependInt32Slot(16, subPartsCountField, 0)
def AddSubPartsCountField(builder, subPartsCountField):
    return CharacterExcelAddSubPartsCountField(builder, subPartsCountField)
def CharacterExcelAddTacticRoleField(builder, tacticRoleField): builder.PrependFloat32Slot(17, tacticRoleField, 0.0)
def AddTacticRoleField(builder, tacticRoleField):
    return CharacterExcelAddTacticRoleField(builder, tacticRoleField)
def CharacterExcelAddWeaponTypeField(builder, weaponTypeField): builder.PrependInt32Slot(18, weaponTypeField, 0)
def AddWeaponTypeField(builder, weaponTypeField):
    return CharacterExcelAddWeaponTypeField(builder, weaponTypeField)
def CharacterExcelAddTacticRangeField(builder, tacticRangeField): builder.PrependInt32Slot(19, tacticRangeField, 0)
def AddTacticRangeField(builder, tacticRangeField):
    return CharacterExcelAddTacticRangeField(builder, tacticRangeField)
def CharacterExcelAddBulletTypeField(builder, bulletTypeField): builder.PrependInt32Slot(20, bulletTypeField, 0)
def AddBulletTypeField(builder, bulletTypeField):
    return CharacterExcelAddBulletTypeField(builder, bulletTypeField)
def CharacterExcelAddArmorTypeField(builder, armorTypeField): builder.PrependInt32Slot(21, armorTypeField, 0)
def AddArmorTypeField(builder, armorTypeField):
    return CharacterExcelAddArmorTypeField(builder, armorTypeField)
def CharacterExcelAddAimIKTypeField(builder, aimIKTypeField): builder.PrependInt32Slot(22, aimIKTypeField, 0)
def AddAimIKTypeField(builder, aimIKTypeField):
    return CharacterExcelAddAimIKTypeField(builder, aimIKTypeField)
def CharacterExcelAddSchoolField(builder, schoolField): builder.PrependInt32Slot(23, schoolField, 0)
def AddSchoolField(builder, schoolField):
    return CharacterExcelAddSchoolField(builder, schoolField)
def CharacterExcelAddClubField(builder, clubField): builder.PrependInt32Slot(24, clubField, 0)
def AddClubField(builder, clubField):
    return CharacterExcelAddClubField(builder, clubField)
def CharacterExcelAddDefaultStarGradeField(builder, defaultStarGradeField): builder.PrependInt32Slot(25, defaultStarGradeField, 0)
def AddDefaultStarGradeField(builder, defaultStarGradeField):
    return CharacterExcelAddDefaultStarGradeField(builder, defaultStarGradeField)
def CharacterExcelAddMaxStarGradeField(builder, maxStarGradeField): builder.PrependInt32Slot(26, maxStarGradeField, 0)
def AddMaxStarGradeField(builder, maxStarGradeField):
    return CharacterExcelAddMaxStarGradeField(builder, maxStarGradeField)
def CharacterExcelAddStatLevelUpTypeField(builder, statLevelUpTypeField): builder.PrependInt32Slot(27, statLevelUpTypeField, 0)
def AddStatLevelUpTypeField(builder, statLevelUpTypeField):
    return CharacterExcelAddStatLevelUpTypeField(builder, statLevelUpTypeField)
def CharacterExcelAddSquadTypeField(builder, squadTypeField): builder.PrependInt32Slot(28, squadTypeField, 0)
def AddSquadTypeField(builder, squadTypeField):
    return CharacterExcelAddSquadTypeField(builder, squadTypeField)
def CharacterExcelAddJumpableField(builder, jumpableField): builder.PrependBoolSlot(29, jumpableField, 0)
def AddJumpableField(builder, jumpableField):
    return CharacterExcelAddJumpableField(builder, jumpableField)
def CharacterExcelAddPersonalityIdField(builder, personalityIdField): builder.PrependInt32Slot(30, personalityIdField, 0)
def AddPersonalityIdField(builder, personalityIdField):
    return CharacterExcelAddPersonalityIdField(builder, personalityIdField)
def CharacterExcelAddCharacterAIIdField(builder, characterAIIdField): builder.PrependInt32Slot(31, characterAIIdField, 0)
def AddCharacterAIIdField(builder, characterAIIdField):
    return CharacterExcelAddCharacterAIIdField(builder, characterAIIdField)
def CharacterExcelAddExternalBTIdField(builder, externalBTIdField): builder.PrependInt32Slot(32, externalBTIdField, 0)
def AddExternalBTIdField(builder, externalBTIdField):
    return CharacterExcelAddExternalBTIdField(builder, externalBTIdField)
def CharacterExcelAddMainCombatStyleIdField(builder, mainCombatStyleIdField): builder.PrependInt32Slot(33, mainCombatStyleIdField, 0)
def AddMainCombatStyleIdField(builder, mainCombatStyleIdField):
    return CharacterExcelAddMainCombatStyleIdField(builder, mainCombatStyleIdField)
def CharacterExcelAddCombatStyleIndexField(builder, combatStyleIndexField): builder.PrependInt32Slot(34, combatStyleIndexField, 0)
def AddCombatStyleIndexField(builder, combatStyleIndexField):
    return CharacterExcelAddCombatStyleIndexField(builder, combatStyleIndexField)
def CharacterExcelAddUseRepStyleOnCharacterGrowthField(builder, useRepStyleOnCharacterGrowthField): builder.PrependBoolSlot(35, useRepStyleOnCharacterGrowthField, 0)
def AddUseRepStyleOnCharacterGrowthField(builder, useRepStyleOnCharacterGrowthField):
    return CharacterExcelAddUseRepStyleOnCharacterGrowthField(builder, useRepStyleOnCharacterGrowthField)
def CharacterExcelAddScenarioCharacterField(builder, scenarioCharacterField): builder.PrependUOffsetTRelativeSlot(36, flatbuffers.number_types.UOffsetTFlags.py_type(scenarioCharacterField), 0)
def AddScenarioCharacterField(builder, scenarioCharacterField):
    return CharacterExcelAddScenarioCharacterField(builder, scenarioCharacterField)
def CharacterExcelAddSpawnTemplateIdField(builder, spawnTemplateIdField): builder.PrependUint32Slot(37, spawnTemplateIdField, 0)
def AddSpawnTemplateIdField(builder, spawnTemplateIdField):
    return CharacterExcelAddSpawnTemplateIdField(builder, spawnTemplateIdField)
def CharacterExcelAddFavorLevelupTypeField(builder, favorLevelupTypeField): builder.PrependInt32Slot(38, favorLevelupTypeField, 0)
def AddFavorLevelupTypeField(builder, favorLevelupTypeField):
    return CharacterExcelAddFavorLevelupTypeField(builder, favorLevelupTypeField)
def CharacterExcelAddEquipmentSlotField(builder, equipmentSlotField): builder.PrependUOffsetTRelativeSlot(39, flatbuffers.number_types.UOffsetTFlags.py_type(equipmentSlotField), 0)
def AddEquipmentSlotField(builder, equipmentSlotField):
    return CharacterExcelAddEquipmentSlotField(builder, equipmentSlotField)
def CharacterExcelStartEquipmentSlotFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartEquipmentSlotFieldVector(builder, numElems):
    return CharacterExcelStartEquipmentSlotFieldVector(builder, numElems)
def CharacterExcelAddWeaponLocalizeIdField(builder, weaponLocalizeIdField): builder.PrependUint32Slot(40, weaponLocalizeIdField, 0)
def AddWeaponLocalizeIdField(builder, weaponLocalizeIdField):
    return CharacterExcelAddWeaponLocalizeIdField(builder, weaponLocalizeIdField)
def CharacterExcelAddDisplayEnemyInfoField(builder, displayEnemyInfoField): builder.PrependBoolSlot(41, displayEnemyInfoField, 0)
def AddDisplayEnemyInfoField(builder, displayEnemyInfoField):
    return CharacterExcelAddDisplayEnemyInfoField(builder, displayEnemyInfoField)
def CharacterExcelAddBodyRadiusField(builder, bodyRadiusField): builder.PrependInt32Slot(42, bodyRadiusField, 0)
def AddBodyRadiusField(builder, bodyRadiusField):
    return CharacterExcelAddBodyRadiusField(builder, bodyRadiusField)
def CharacterExcelAddRandomEffectRadiusField(builder, randomEffectRadiusField): builder.PrependInt32Slot(43, randomEffectRadiusField, 0)
def AddRandomEffectRadiusField(builder, randomEffectRadiusField):
    return CharacterExcelAddRandomEffectRadiusField(builder, randomEffectRadiusField)
def CharacterExcelAddTargetGuideScaleField(builder, targetGuideScaleField): builder.PrependFloat32Slot(44, targetGuideScaleField, 0.0)
def AddTargetGuideScaleField(builder, targetGuideScaleField):
    return CharacterExcelAddTargetGuideScaleField(builder, targetGuideScaleField)
def CharacterExcelAddHPBarHideField(builder, hPBarHideField): builder.PrependBoolSlot(45, hPBarHideField, 0)
def AddHPBarHideField(builder, hPBarHideField):
    return CharacterExcelAddHPBarHideField(builder, hPBarHideField)
def CharacterExcelAddHpBarHeightField(builder, hpBarHeightField): builder.PrependFloat32Slot(46, hpBarHeightField, 0.0)
def AddHpBarHeightField(builder, hpBarHeightField):
    return CharacterExcelAddHpBarHeightField(builder, hpBarHeightField)
def CharacterExcelAddHighlightFloaterHeightField(builder, highlightFloaterHeightField): builder.PrependFloat32Slot(47, highlightFloaterHeightField, 0.0)
def AddHighlightFloaterHeightField(builder, highlightFloaterHeightField):
    return CharacterExcelAddHighlightFloaterHeightField(builder, highlightFloaterHeightField)
def CharacterExcelAddEmojiOffsetXField(builder, emojiOffsetXField): builder.PrependFloat32Slot(48, emojiOffsetXField, 0.0)
def AddEmojiOffsetXField(builder, emojiOffsetXField):
    return CharacterExcelAddEmojiOffsetXField(builder, emojiOffsetXField)
def CharacterExcelAddEmojiOffsetYField(builder, emojiOffsetYField): builder.PrependFloat32Slot(49, emojiOffsetYField, 0.0)
def AddEmojiOffsetYField(builder, emojiOffsetYField):
    return CharacterExcelAddEmojiOffsetYField(builder, emojiOffsetYField)
def CharacterExcelAddMoveStartFrameField(builder, moveStartFrameField): builder.PrependInt32Slot(50, moveStartFrameField, 0)
def AddMoveStartFrameField(builder, moveStartFrameField):
    return CharacterExcelAddMoveStartFrameField(builder, moveStartFrameField)
def CharacterExcelAddMoveEndFrameField(builder, moveEndFrameField): builder.PrependInt32Slot(51, moveEndFrameField, 0)
def AddMoveEndFrameField(builder, moveEndFrameField):
    return CharacterExcelAddMoveEndFrameField(builder, moveEndFrameField)
def CharacterExcelAddJumpMotionFrameField(builder, jumpMotionFrameField): builder.PrependInt32Slot(52, jumpMotionFrameField, 0)
def AddJumpMotionFrameField(builder, jumpMotionFrameField):
    return CharacterExcelAddJumpMotionFrameField(builder, jumpMotionFrameField)
def CharacterExcelAddAppearFrameField(builder, appearFrameField): builder.PrependInt32Slot(53, appearFrameField, 0)
def AddAppearFrameField(builder, appearFrameField):
    return CharacterExcelAddAppearFrameField(builder, appearFrameField)
def CharacterExcelAddCanMoveField(builder, canMoveField): builder.PrependBoolSlot(54, canMoveField, 0)
def AddCanMoveField(builder, canMoveField):
    return CharacterExcelAddCanMoveField(builder, canMoveField)
def CharacterExcelAddCanFixField(builder, canFixField): builder.PrependBoolSlot(55, canFixField, 0)
def AddCanFixField(builder, canFixField):
    return CharacterExcelAddCanFixField(builder, canFixField)
def CharacterExcelAddCanCrowdControlField(builder, canCrowdControlField): builder.PrependBoolSlot(56, canCrowdControlField, 0)
def AddCanCrowdControlField(builder, canCrowdControlField):
    return CharacterExcelAddCanCrowdControlField(builder, canCrowdControlField)
def CharacterExcelAddCanBattleItemMoveField(builder, canBattleItemMoveField): builder.PrependBoolSlot(57, canBattleItemMoveField, 0)
def AddCanBattleItemMoveField(builder, canBattleItemMoveField):
    return CharacterExcelAddCanBattleItemMoveField(builder, canBattleItemMoveField)
def CharacterExcelAddIgnoreObstacleField(builder, ignoreObstacleField): builder.PrependBoolSlot(58, ignoreObstacleField, 0)
def AddIgnoreObstacleField(builder, ignoreObstacleField):
    return CharacterExcelAddIgnoreObstacleField(builder, ignoreObstacleField)
def CharacterExcelAddIsAirUnitField(builder, isAirUnitField): builder.PrependBoolSlot(59, isAirUnitField, 0)
def AddIsAirUnitField(builder, isAirUnitField):
    return CharacterExcelAddIsAirUnitField(builder, isAirUnitField)
def CharacterExcelAddAirUnitHeightField(builder, airUnitHeightField): builder.PrependInt32Slot(60, airUnitHeightField, 0)
def AddAirUnitHeightField(builder, airUnitHeightField):
    return CharacterExcelAddAirUnitHeightField(builder, airUnitHeightField)
def CharacterExcelAddTagsField(builder, tagsField): builder.PrependUOffsetTRelativeSlot(61, flatbuffers.number_types.UOffsetTFlags.py_type(tagsField), 0)
def AddTagsField(builder, tagsField):
    return CharacterExcelAddTagsField(builder, tagsField)
def CharacterExcelStartTagsFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartTagsFieldVector(builder, numElems):
    return CharacterExcelStartTagsFieldVector(builder, numElems)
def CharacterExcelAddSecretStoneItemIdField(builder, secretStoneItemIdField): builder.PrependInt32Slot(62, secretStoneItemIdField, 0)
def AddSecretStoneItemIdField(builder, secretStoneItemIdField):
    return CharacterExcelAddSecretStoneItemIdField(builder, secretStoneItemIdField)
def CharacterExcelAddSecretStoneItemAmountField(builder, secretStoneItemAmountField): builder.PrependInt32Slot(63, secretStoneItemAmountField, 0)
def AddSecretStoneItemAmountField(builder, secretStoneItemAmountField):
    return CharacterExcelAddSecretStoneItemAmountField(builder, secretStoneItemAmountField)
def CharacterExcelAddCharacterPieceItemIdField(builder, characterPieceItemIdField): builder.PrependInt32Slot(64, characterPieceItemIdField, 0)
def AddCharacterPieceItemIdField(builder, characterPieceItemIdField):
    return CharacterExcelAddCharacterPieceItemIdField(builder, characterPieceItemIdField)
def CharacterExcelAddCharacterPieceItemAmountField(builder, characterPieceItemAmountField): builder.PrependInt32Slot(65, characterPieceItemAmountField, 0)
def AddCharacterPieceItemAmountField(builder, characterPieceItemAmountField):
    return CharacterExcelAddCharacterPieceItemAmountField(builder, characterPieceItemAmountField)
def CharacterExcelAddCombineRecipeIdField(builder, combineRecipeIdField): builder.PrependInt32Slot(66, combineRecipeIdField, 0)
def AddCombineRecipeIdField(builder, combineRecipeIdField):
    return CharacterExcelAddCombineRecipeIdField(builder, combineRecipeIdField)
def CharacterExcelEnd(builder): return builder.EndObject()
def End(builder):
    return CharacterExcelEnd(builder)