# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EquipmentExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EquipmentExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEquipmentExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EquipmentExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EquipmentExcel
    def IdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EquipmentExcel
    def EquipmentCategoryField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EquipmentExcel
    def RarityField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EquipmentExcel
    def LocalizeEtcIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # EquipmentExcel
    def WearField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # EquipmentExcel
    def MaxLevelField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EquipmentExcel
    def RecipeIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EquipmentExcel
    def TierInitField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EquipmentExcel
    def NextTierEquipmentField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EquipmentExcel
    def StackableMaxField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EquipmentExcel
    def IconField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EquipmentExcel
    def ImageNameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EquipmentExcel
    def TagsField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # EquipmentExcel
    def TagsFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # EquipmentExcel
    def TagsFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EquipmentExcel
    def TagsFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

    # EquipmentExcel
    def CraftQualityTier0Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EquipmentExcel
    def CraftQualityTier1Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EquipmentExcel
    def CraftQualityTier2Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EquipmentExcel
    def ShiftingCraftQualityField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EquipmentExcel
    def ShopCategoryField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # EquipmentExcel
    def ShopCategoryFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # EquipmentExcel
    def ShopCategoryFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EquipmentExcel
    def ShopCategoryFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        return o == 0

    # EquipmentExcel
    def ShortcutTypeIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EquipmentExcel
    def RedirectItemIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def EquipmentExcelStart(builder): builder.StartObject(20)
def Start(builder):
    return EquipmentExcelStart(builder)
def EquipmentExcelAddIdField(builder, idField): builder.PrependInt32Slot(0, idField, 0)
def AddIdField(builder, idField):
    return EquipmentExcelAddIdField(builder, idField)
def EquipmentExcelAddEquipmentCategoryField(builder, equipmentCategoryField): builder.PrependInt32Slot(1, equipmentCategoryField, 0)
def AddEquipmentCategoryField(builder, equipmentCategoryField):
    return EquipmentExcelAddEquipmentCategoryField(builder, equipmentCategoryField)
def EquipmentExcelAddRarityField(builder, rarityField): builder.PrependInt32Slot(2, rarityField, 0)
def AddRarityField(builder, rarityField):
    return EquipmentExcelAddRarityField(builder, rarityField)
def EquipmentExcelAddLocalizeEtcIdField(builder, localizeEtcIdField): builder.PrependUint32Slot(3, localizeEtcIdField, 0)
def AddLocalizeEtcIdField(builder, localizeEtcIdField):
    return EquipmentExcelAddLocalizeEtcIdField(builder, localizeEtcIdField)
def EquipmentExcelAddWearField(builder, wearField): builder.PrependBoolSlot(4, wearField, 0)
def AddWearField(builder, wearField):
    return EquipmentExcelAddWearField(builder, wearField)
def EquipmentExcelAddMaxLevelField(builder, maxLevelField): builder.PrependInt32Slot(5, maxLevelField, 0)
def AddMaxLevelField(builder, maxLevelField):
    return EquipmentExcelAddMaxLevelField(builder, maxLevelField)
def EquipmentExcelAddRecipeIdField(builder, recipeIdField): builder.PrependInt32Slot(6, recipeIdField, 0)
def AddRecipeIdField(builder, recipeIdField):
    return EquipmentExcelAddRecipeIdField(builder, recipeIdField)
def EquipmentExcelAddTierInitField(builder, tierInitField): builder.PrependInt32Slot(7, tierInitField, 0)
def AddTierInitField(builder, tierInitField):
    return EquipmentExcelAddTierInitField(builder, tierInitField)
def EquipmentExcelAddNextTierEquipmentField(builder, nextTierEquipmentField): builder.PrependInt32Slot(8, nextTierEquipmentField, 0)
def AddNextTierEquipmentField(builder, nextTierEquipmentField):
    return EquipmentExcelAddNextTierEquipmentField(builder, nextTierEquipmentField)
def EquipmentExcelAddStackableMaxField(builder, stackableMaxField): builder.PrependInt32Slot(9, stackableMaxField, 0)
def AddStackableMaxField(builder, stackableMaxField):
    return EquipmentExcelAddStackableMaxField(builder, stackableMaxField)
def EquipmentExcelAddIconField(builder, iconField): builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(iconField), 0)
def AddIconField(builder, iconField):
    return EquipmentExcelAddIconField(builder, iconField)
def EquipmentExcelAddImageNameField(builder, imageNameField): builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(imageNameField), 0)
def AddImageNameField(builder, imageNameField):
    return EquipmentExcelAddImageNameField(builder, imageNameField)
def EquipmentExcelAddTagsField(builder, tagsField): builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(tagsField), 0)
def AddTagsField(builder, tagsField):
    return EquipmentExcelAddTagsField(builder, tagsField)
def EquipmentExcelStartTagsFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartTagsFieldVector(builder, numElems):
    return EquipmentExcelStartTagsFieldVector(builder, numElems)
def EquipmentExcelAddCraftQualityTier0Field(builder, craftQualityTier0Field): builder.PrependInt32Slot(13, craftQualityTier0Field, 0)
def AddCraftQualityTier0Field(builder, craftQualityTier0Field):
    return EquipmentExcelAddCraftQualityTier0Field(builder, craftQualityTier0Field)
def EquipmentExcelAddCraftQualityTier1Field(builder, craftQualityTier1Field): builder.PrependInt32Slot(14, craftQualityTier1Field, 0)
def AddCraftQualityTier1Field(builder, craftQualityTier1Field):
    return EquipmentExcelAddCraftQualityTier1Field(builder, craftQualityTier1Field)
def EquipmentExcelAddCraftQualityTier2Field(builder, craftQualityTier2Field): builder.PrependInt32Slot(15, craftQualityTier2Field, 0)
def AddCraftQualityTier2Field(builder, craftQualityTier2Field):
    return EquipmentExcelAddCraftQualityTier2Field(builder, craftQualityTier2Field)
def EquipmentExcelAddShiftingCraftQualityField(builder, shiftingCraftQualityField): builder.PrependInt32Slot(16, shiftingCraftQualityField, 0)
def AddShiftingCraftQualityField(builder, shiftingCraftQualityField):
    return EquipmentExcelAddShiftingCraftQualityField(builder, shiftingCraftQualityField)
def EquipmentExcelAddShopCategoryField(builder, shopCategoryField): builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(shopCategoryField), 0)
def AddShopCategoryField(builder, shopCategoryField):
    return EquipmentExcelAddShopCategoryField(builder, shopCategoryField)
def EquipmentExcelStartShopCategoryFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartShopCategoryFieldVector(builder, numElems):
    return EquipmentExcelStartShopCategoryFieldVector(builder, numElems)
def EquipmentExcelAddShortcutTypeIdField(builder, shortcutTypeIdField): builder.PrependInt32Slot(18, shortcutTypeIdField, 0)
def AddShortcutTypeIdField(builder, shortcutTypeIdField):
    return EquipmentExcelAddShortcutTypeIdField(builder, shortcutTypeIdField)
def EquipmentExcelAddRedirectItemIdField(builder, redirectItemIdField): builder.PrependInt32Slot(19, redirectItemIdField, 0)
def AddRedirectItemIdField(builder, redirectItemIdField):
    return EquipmentExcelAddRedirectItemIdField(builder, redirectItemIdField)
def EquipmentExcelEnd(builder): return builder.EndObject()
def End(builder):
    return EquipmentExcelEnd(builder)