# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventContentConcentrationVoiceExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventContentConcentrationVoiceExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventContentConcentrationVoiceExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventContentConcentrationVoiceExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventContentConcentrationVoiceExcel
    def EventContentIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventContentConcentrationVoiceExcel
    def UniqueIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventContentConcentrationVoiceExcel
    def VoiceConditionField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventContentConcentrationVoiceExcel
    def VoiceClipField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def EventContentConcentrationVoiceExcelStart(builder): builder.StartObject(4)
def Start(builder):
    return EventContentConcentrationVoiceExcelStart(builder)
def EventContentConcentrationVoiceExcelAddEventContentIdField(builder, eventContentIdField): builder.PrependInt32Slot(0, eventContentIdField, 0)
def AddEventContentIdField(builder, eventContentIdField):
    return EventContentConcentrationVoiceExcelAddEventContentIdField(builder, eventContentIdField)
def EventContentConcentrationVoiceExcelAddUniqueIdField(builder, uniqueIdField): builder.PrependInt32Slot(1, uniqueIdField, 0)
def AddUniqueIdField(builder, uniqueIdField):
    return EventContentConcentrationVoiceExcelAddUniqueIdField(builder, uniqueIdField)
def EventContentConcentrationVoiceExcelAddVoiceConditionField(builder, voiceConditionField): builder.PrependInt32Slot(2, voiceConditionField, 0)
def AddVoiceConditionField(builder, voiceConditionField):
    return EventContentConcentrationVoiceExcelAddVoiceConditionField(builder, voiceConditionField)
def EventContentConcentrationVoiceExcelAddVoiceClipField(builder, voiceClipField): builder.PrependUint32Slot(3, voiceClipField, 0)
def AddVoiceClipField(builder, voiceClipField):
    return EventContentConcentrationVoiceExcelAddVoiceClipField(builder, voiceClipField)
def EventContentConcentrationVoiceExcelEnd(builder): return builder.EndObject()
def End(builder):
    return EventContentConcentrationVoiceExcelEnd(builder)