# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FurnitureTemplateElementExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FurnitureTemplateElementExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFurnitureTemplateElementExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FurnitureTemplateElementExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FurnitureTemplateElementExcel
    def FurnitureTemplateIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FurnitureTemplateElementExcel
    def FurnitureIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FurnitureTemplateElementExcel
    def LocationField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FurnitureTemplateElementExcel
    def PositionXField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # FurnitureTemplateElementExcel
    def PositionYField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # FurnitureTemplateElementExcel
    def RotationField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # FurnitureTemplateElementExcel
    def OrderField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def FurnitureTemplateElementExcelStart(builder): builder.StartObject(7)
def Start(builder):
    return FurnitureTemplateElementExcelStart(builder)
def FurnitureTemplateElementExcelAddFurnitureTemplateIdField(builder, furnitureTemplateIdField): builder.PrependInt32Slot(0, furnitureTemplateIdField, 0)
def AddFurnitureTemplateIdField(builder, furnitureTemplateIdField):
    return FurnitureTemplateElementExcelAddFurnitureTemplateIdField(builder, furnitureTemplateIdField)
def FurnitureTemplateElementExcelAddFurnitureIdField(builder, furnitureIdField): builder.PrependInt32Slot(1, furnitureIdField, 0)
def AddFurnitureIdField(builder, furnitureIdField):
    return FurnitureTemplateElementExcelAddFurnitureIdField(builder, furnitureIdField)
def FurnitureTemplateElementExcelAddLocationField(builder, locationField): builder.PrependInt32Slot(2, locationField, 0)
def AddLocationField(builder, locationField):
    return FurnitureTemplateElementExcelAddLocationField(builder, locationField)
def FurnitureTemplateElementExcelAddPositionXField(builder, positionXField): builder.PrependFloat32Slot(3, positionXField, 0.0)
def AddPositionXField(builder, positionXField):
    return FurnitureTemplateElementExcelAddPositionXField(builder, positionXField)
def FurnitureTemplateElementExcelAddPositionYField(builder, positionYField): builder.PrependFloat32Slot(4, positionYField, 0.0)
def AddPositionYField(builder, positionYField):
    return FurnitureTemplateElementExcelAddPositionYField(builder, positionYField)
def FurnitureTemplateElementExcelAddRotationField(builder, rotationField): builder.PrependFloat32Slot(5, rotationField, 0.0)
def AddRotationField(builder, rotationField):
    return FurnitureTemplateElementExcelAddRotationField(builder, rotationField)
def FurnitureTemplateElementExcelAddOrderField(builder, orderField): builder.PrependInt32Slot(6, orderField, 0)
def AddOrderField(builder, orderField):
    return FurnitureTemplateElementExcelAddOrderField(builder, orderField)
def FurnitureTemplateElementExcelEnd(builder): return builder.EndObject()
def End(builder):
    return FurnitureTemplateElementExcelEnd(builder)