# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GroundExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GroundExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGroundExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GroundExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GroundExcel
    def IdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def StageFileNameField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # GroundExcel
    def StageFileNameFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GroundExcel
    def StageFileNameFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # GroundExcel
    def GroundSceneNameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GroundExcel
    def FormationGroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def StageTopographyField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def EnemyBulletTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def EnemyArmorTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def EnemySubArmorTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def LevelNPCField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def LevelMinionField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def LevelEliteField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def LevelChampionField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def LevelBossField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def ObstacleLevelField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def GradeNPCField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def GradeMinionField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def GradeEliteField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def GradeChampionField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def GradeBossField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def PlayerSightPointAddField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def PlayerSightPointRateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def PlayerAttackRangeAddField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def PlayerAttackRangeRateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def EnemySightPointAddField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def EnemySightPointRateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def EnemyAttackRangeAddField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def EnemyAttackRangeRateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def PlayerSkillRangeAddField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def PlayerSkillRangeRateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def EnemySkillRangeAddField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def EnemySkillRangeRateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def PlayerMinimumPositionGapRateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def EnemyMinimumPositionGapRateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def PlayerSightRangeMaxField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GroundExcel
    def EnemySightRangeMaxField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GroundExcel
    def TSSAirUnitHeightField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def IsPhaseBGMField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GroundExcel
    def BGMIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def WarningUIField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(80))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GroundExcel
    def TSSHatchOpenField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(82))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GroundExcel
    def ForcedTacticSpeedField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(84))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def ForcedSkillUseField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(86))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def ShowNPCSkillCutInField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(88))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def ImmuneHitBeforeTimeOutEndField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(90))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GroundExcel
    def UIBattleHideFromScratchField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(92))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GroundExcel
    def UIEnemyCountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(94))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def BattleReadyTimelinePathField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(96))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GroundExcel
    def BeforeVictoryTimelinePathField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(98))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GroundExcel
    def SkipBattleEndField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(100))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GroundExcel
    def HideNPCWhenBattleEndField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(102))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GroundExcel
    def CoverPointOffField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(104))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GroundExcel
    def UIHpScaleField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(106))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GroundExcel
    def UIEmojiScaleField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(108))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GroundExcel
    def UISkillMainLogScaleField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(110))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # GroundExcel
    def EffectCountLimitField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(112))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def CarrierSkillGroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(114))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GroundExcel
    def AllyPassiveSkillIdField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(116))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # GroundExcel
    def AllyPassiveSkillIdFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(116))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GroundExcel
    def AllyPassiveSkillIdFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(116))
        return o == 0

    # GroundExcel
    def AllyPassiveSkillLevelField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(118))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GroundExcel
    def AllyPassiveSkillLevelFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(118))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GroundExcel
    def AllyPassiveSkillLevelFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(118))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GroundExcel
    def AllyPassiveSkillLevelFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(118))
        return o == 0

    # GroundExcel
    def EnemyPassiveSkillIdField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(120))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # GroundExcel
    def EnemyPassiveSkillIdFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(120))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GroundExcel
    def EnemyPassiveSkillIdFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(120))
        return o == 0

    # GroundExcel
    def EnemyPassiveSkillLevelField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(122))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # GroundExcel
    def EnemyPassiveSkillLevelFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(122))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # GroundExcel
    def EnemyPassiveSkillLevelFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(122))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GroundExcel
    def EnemyPassiveSkillLevelFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(122))
        return o == 0

def GroundExcelStart(builder): builder.StartObject(60)
def Start(builder):
    return GroundExcelStart(builder)
def GroundExcelAddIdField(builder, idField): builder.PrependInt32Slot(0, idField, 0)
def AddIdField(builder, idField):
    return GroundExcelAddIdField(builder, idField)
def GroundExcelAddStageFileNameField(builder, stageFileNameField): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(stageFileNameField), 0)
def AddStageFileNameField(builder, stageFileNameField):
    return GroundExcelAddStageFileNameField(builder, stageFileNameField)
def GroundExcelStartStageFileNameFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartStageFileNameFieldVector(builder, numElems):
    return GroundExcelStartStageFileNameFieldVector(builder, numElems)
def GroundExcelAddGroundSceneNameField(builder, groundSceneNameField): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(groundSceneNameField), 0)
def AddGroundSceneNameField(builder, groundSceneNameField):
    return GroundExcelAddGroundSceneNameField(builder, groundSceneNameField)
def GroundExcelAddFormationGroupIdField(builder, formationGroupIdField): builder.PrependInt32Slot(3, formationGroupIdField, 0)
def AddFormationGroupIdField(builder, formationGroupIdField):
    return GroundExcelAddFormationGroupIdField(builder, formationGroupIdField)
def GroundExcelAddStageTopographyField(builder, stageTopographyField): builder.PrependInt32Slot(4, stageTopographyField, 0)
def AddStageTopographyField(builder, stageTopographyField):
    return GroundExcelAddStageTopographyField(builder, stageTopographyField)
def GroundExcelAddEnemyBulletTypeField(builder, enemyBulletTypeField): builder.PrependInt32Slot(5, enemyBulletTypeField, 0)
def AddEnemyBulletTypeField(builder, enemyBulletTypeField):
    return GroundExcelAddEnemyBulletTypeField(builder, enemyBulletTypeField)
def GroundExcelAddEnemyArmorTypeField(builder, enemyArmorTypeField): builder.PrependInt32Slot(6, enemyArmorTypeField, 0)
def AddEnemyArmorTypeField(builder, enemyArmorTypeField):
    return GroundExcelAddEnemyArmorTypeField(builder, enemyArmorTypeField)
def GroundExcelAddEnemySubArmorTypeField(builder, enemySubArmorTypeField): builder.PrependInt32Slot(7, enemySubArmorTypeField, 0)
def AddEnemySubArmorTypeField(builder, enemySubArmorTypeField):
    return GroundExcelAddEnemySubArmorTypeField(builder, enemySubArmorTypeField)
def GroundExcelAddLevelNPCField(builder, levelNPCField): builder.PrependInt32Slot(8, levelNPCField, 0)
def AddLevelNPCField(builder, levelNPCField):
    return GroundExcelAddLevelNPCField(builder, levelNPCField)
def GroundExcelAddLevelMinionField(builder, levelMinionField): builder.PrependInt32Slot(9, levelMinionField, 0)
def AddLevelMinionField(builder, levelMinionField):
    return GroundExcelAddLevelMinionField(builder, levelMinionField)
def GroundExcelAddLevelEliteField(builder, levelEliteField): builder.PrependInt32Slot(10, levelEliteField, 0)
def AddLevelEliteField(builder, levelEliteField):
    return GroundExcelAddLevelEliteField(builder, levelEliteField)
def GroundExcelAddLevelChampionField(builder, levelChampionField): builder.PrependInt32Slot(11, levelChampionField, 0)
def AddLevelChampionField(builder, levelChampionField):
    return GroundExcelAddLevelChampionField(builder, levelChampionField)
def GroundExcelAddLevelBossField(builder, levelBossField): builder.PrependInt32Slot(12, levelBossField, 0)
def AddLevelBossField(builder, levelBossField):
    return GroundExcelAddLevelBossField(builder, levelBossField)
def GroundExcelAddObstacleLevelField(builder, obstacleLevelField): builder.PrependInt32Slot(13, obstacleLevelField, 0)
def AddObstacleLevelField(builder, obstacleLevelField):
    return GroundExcelAddObstacleLevelField(builder, obstacleLevelField)
def GroundExcelAddGradeNPCField(builder, gradeNPCField): builder.PrependInt32Slot(14, gradeNPCField, 0)
def AddGradeNPCField(builder, gradeNPCField):
    return GroundExcelAddGradeNPCField(builder, gradeNPCField)
def GroundExcelAddGradeMinionField(builder, gradeMinionField): builder.PrependInt32Slot(15, gradeMinionField, 0)
def AddGradeMinionField(builder, gradeMinionField):
    return GroundExcelAddGradeMinionField(builder, gradeMinionField)
def GroundExcelAddGradeEliteField(builder, gradeEliteField): builder.PrependInt32Slot(16, gradeEliteField, 0)
def AddGradeEliteField(builder, gradeEliteField):
    return GroundExcelAddGradeEliteField(builder, gradeEliteField)
def GroundExcelAddGradeChampionField(builder, gradeChampionField): builder.PrependInt32Slot(17, gradeChampionField, 0)
def AddGradeChampionField(builder, gradeChampionField):
    return GroundExcelAddGradeChampionField(builder, gradeChampionField)
def GroundExcelAddGradeBossField(builder, gradeBossField): builder.PrependInt32Slot(18, gradeBossField, 0)
def AddGradeBossField(builder, gradeBossField):
    return GroundExcelAddGradeBossField(builder, gradeBossField)
def GroundExcelAddPlayerSightPointAddField(builder, playerSightPointAddField): builder.PrependInt32Slot(19, playerSightPointAddField, 0)
def AddPlayerSightPointAddField(builder, playerSightPointAddField):
    return GroundExcelAddPlayerSightPointAddField(builder, playerSightPointAddField)
def GroundExcelAddPlayerSightPointRateField(builder, playerSightPointRateField): builder.PrependInt32Slot(20, playerSightPointRateField, 0)
def AddPlayerSightPointRateField(builder, playerSightPointRateField):
    return GroundExcelAddPlayerSightPointRateField(builder, playerSightPointRateField)
def GroundExcelAddPlayerAttackRangeAddField(builder, playerAttackRangeAddField): builder.PrependInt32Slot(21, playerAttackRangeAddField, 0)
def AddPlayerAttackRangeAddField(builder, playerAttackRangeAddField):
    return GroundExcelAddPlayerAttackRangeAddField(builder, playerAttackRangeAddField)
def GroundExcelAddPlayerAttackRangeRateField(builder, playerAttackRangeRateField): builder.PrependInt32Slot(22, playerAttackRangeRateField, 0)
def AddPlayerAttackRangeRateField(builder, playerAttackRangeRateField):
    return GroundExcelAddPlayerAttackRangeRateField(builder, playerAttackRangeRateField)
def GroundExcelAddEnemySightPointAddField(builder, enemySightPointAddField): builder.PrependInt32Slot(23, enemySightPointAddField, 0)
def AddEnemySightPointAddField(builder, enemySightPointAddField):
    return GroundExcelAddEnemySightPointAddField(builder, enemySightPointAddField)
def GroundExcelAddEnemySightPointRateField(builder, enemySightPointRateField): builder.PrependInt32Slot(24, enemySightPointRateField, 0)
def AddEnemySightPointRateField(builder, enemySightPointRateField):
    return GroundExcelAddEnemySightPointRateField(builder, enemySightPointRateField)
def GroundExcelAddEnemyAttackRangeAddField(builder, enemyAttackRangeAddField): builder.PrependInt32Slot(25, enemyAttackRangeAddField, 0)
def AddEnemyAttackRangeAddField(builder, enemyAttackRangeAddField):
    return GroundExcelAddEnemyAttackRangeAddField(builder, enemyAttackRangeAddField)
def GroundExcelAddEnemyAttackRangeRateField(builder, enemyAttackRangeRateField): builder.PrependInt32Slot(26, enemyAttackRangeRateField, 0)
def AddEnemyAttackRangeRateField(builder, enemyAttackRangeRateField):
    return GroundExcelAddEnemyAttackRangeRateField(builder, enemyAttackRangeRateField)
def GroundExcelAddPlayerSkillRangeAddField(builder, playerSkillRangeAddField): builder.PrependInt32Slot(27, playerSkillRangeAddField, 0)
def AddPlayerSkillRangeAddField(builder, playerSkillRangeAddField):
    return GroundExcelAddPlayerSkillRangeAddField(builder, playerSkillRangeAddField)
def GroundExcelAddPlayerSkillRangeRateField(builder, playerSkillRangeRateField): builder.PrependInt32Slot(28, playerSkillRangeRateField, 0)
def AddPlayerSkillRangeRateField(builder, playerSkillRangeRateField):
    return GroundExcelAddPlayerSkillRangeRateField(builder, playerSkillRangeRateField)
def GroundExcelAddEnemySkillRangeAddField(builder, enemySkillRangeAddField): builder.PrependInt32Slot(29, enemySkillRangeAddField, 0)
def AddEnemySkillRangeAddField(builder, enemySkillRangeAddField):
    return GroundExcelAddEnemySkillRangeAddField(builder, enemySkillRangeAddField)
def GroundExcelAddEnemySkillRangeRateField(builder, enemySkillRangeRateField): builder.PrependInt32Slot(30, enemySkillRangeRateField, 0)
def AddEnemySkillRangeRateField(builder, enemySkillRangeRateField):
    return GroundExcelAddEnemySkillRangeRateField(builder, enemySkillRangeRateField)
def GroundExcelAddPlayerMinimumPositionGapRateField(builder, playerMinimumPositionGapRateField): builder.PrependInt32Slot(31, playerMinimumPositionGapRateField, 0)
def AddPlayerMinimumPositionGapRateField(builder, playerMinimumPositionGapRateField):
    return GroundExcelAddPlayerMinimumPositionGapRateField(builder, playerMinimumPositionGapRateField)
def GroundExcelAddEnemyMinimumPositionGapRateField(builder, enemyMinimumPositionGapRateField): builder.PrependInt32Slot(32, enemyMinimumPositionGapRateField, 0)
def AddEnemyMinimumPositionGapRateField(builder, enemyMinimumPositionGapRateField):
    return GroundExcelAddEnemyMinimumPositionGapRateField(builder, enemyMinimumPositionGapRateField)
def GroundExcelAddPlayerSightRangeMaxField(builder, playerSightRangeMaxField): builder.PrependBoolSlot(33, playerSightRangeMaxField, 0)
def AddPlayerSightRangeMaxField(builder, playerSightRangeMaxField):
    return GroundExcelAddPlayerSightRangeMaxField(builder, playerSightRangeMaxField)
def GroundExcelAddEnemySightRangeMaxField(builder, enemySightRangeMaxField): builder.PrependBoolSlot(34, enemySightRangeMaxField, 0)
def AddEnemySightRangeMaxField(builder, enemySightRangeMaxField):
    return GroundExcelAddEnemySightRangeMaxField(builder, enemySightRangeMaxField)
def GroundExcelAddTSSAirUnitHeightField(builder, tSSAirUnitHeightField): builder.PrependInt32Slot(35, tSSAirUnitHeightField, 0)
def AddTSSAirUnitHeightField(builder, tSSAirUnitHeightField):
    return GroundExcelAddTSSAirUnitHeightField(builder, tSSAirUnitHeightField)
def GroundExcelAddIsPhaseBGMField(builder, isPhaseBGMField): builder.PrependBoolSlot(36, isPhaseBGMField, 0)
def AddIsPhaseBGMField(builder, isPhaseBGMField):
    return GroundExcelAddIsPhaseBGMField(builder, isPhaseBGMField)
def GroundExcelAddBGMIdField(builder, bGMIdField): builder.PrependInt32Slot(37, bGMIdField, 0)
def AddBGMIdField(builder, bGMIdField):
    return GroundExcelAddBGMIdField(builder, bGMIdField)
def GroundExcelAddWarningUIField(builder, warningUIField): builder.PrependBoolSlot(38, warningUIField, 0)
def AddWarningUIField(builder, warningUIField):
    return GroundExcelAddWarningUIField(builder, warningUIField)
def GroundExcelAddTSSHatchOpenField(builder, tSSHatchOpenField): builder.PrependBoolSlot(39, tSSHatchOpenField, 0)
def AddTSSHatchOpenField(builder, tSSHatchOpenField):
    return GroundExcelAddTSSHatchOpenField(builder, tSSHatchOpenField)
def GroundExcelAddForcedTacticSpeedField(builder, forcedTacticSpeedField): builder.PrependInt32Slot(40, forcedTacticSpeedField, 0)
def AddForcedTacticSpeedField(builder, forcedTacticSpeedField):
    return GroundExcelAddForcedTacticSpeedField(builder, forcedTacticSpeedField)
def GroundExcelAddForcedSkillUseField(builder, forcedSkillUseField): builder.PrependInt32Slot(41, forcedSkillUseField, 0)
def AddForcedSkillUseField(builder, forcedSkillUseField):
    return GroundExcelAddForcedSkillUseField(builder, forcedSkillUseField)
def GroundExcelAddShowNPCSkillCutInField(builder, showNPCSkillCutInField): builder.PrependInt32Slot(42, showNPCSkillCutInField, 0)
def AddShowNPCSkillCutInField(builder, showNPCSkillCutInField):
    return GroundExcelAddShowNPCSkillCutInField(builder, showNPCSkillCutInField)
def GroundExcelAddImmuneHitBeforeTimeOutEndField(builder, immuneHitBeforeTimeOutEndField): builder.PrependBoolSlot(43, immuneHitBeforeTimeOutEndField, 0)
def AddImmuneHitBeforeTimeOutEndField(builder, immuneHitBeforeTimeOutEndField):
    return GroundExcelAddImmuneHitBeforeTimeOutEndField(builder, immuneHitBeforeTimeOutEndField)
def GroundExcelAddUIBattleHideFromScratchField(builder, uIBattleHideFromScratchField): builder.PrependBoolSlot(44, uIBattleHideFromScratchField, 0)
def AddUIBattleHideFromScratchField(builder, uIBattleHideFromScratchField):
    return GroundExcelAddUIBattleHideFromScratchField(builder, uIBattleHideFromScratchField)
def GroundExcelAddUIEnemyCountField(builder, uIEnemyCountField): builder.PrependInt32Slot(45, uIEnemyCountField, 0)
def AddUIEnemyCountField(builder, uIEnemyCountField):
    return GroundExcelAddUIEnemyCountField(builder, uIEnemyCountField)
def GroundExcelAddBattleReadyTimelinePathField(builder, battleReadyTimelinePathField): builder.PrependUOffsetTRelativeSlot(46, flatbuffers.number_types.UOffsetTFlags.py_type(battleReadyTimelinePathField), 0)
def AddBattleReadyTimelinePathField(builder, battleReadyTimelinePathField):
    return GroundExcelAddBattleReadyTimelinePathField(builder, battleReadyTimelinePathField)
def GroundExcelAddBeforeVictoryTimelinePathField(builder, beforeVictoryTimelinePathField): builder.PrependUOffsetTRelativeSlot(47, flatbuffers.number_types.UOffsetTFlags.py_type(beforeVictoryTimelinePathField), 0)
def AddBeforeVictoryTimelinePathField(builder, beforeVictoryTimelinePathField):
    return GroundExcelAddBeforeVictoryTimelinePathField(builder, beforeVictoryTimelinePathField)
def GroundExcelAddSkipBattleEndField(builder, skipBattleEndField): builder.PrependBoolSlot(48, skipBattleEndField, 0)
def AddSkipBattleEndField(builder, skipBattleEndField):
    return GroundExcelAddSkipBattleEndField(builder, skipBattleEndField)
def GroundExcelAddHideNPCWhenBattleEndField(builder, hideNPCWhenBattleEndField): builder.PrependBoolSlot(49, hideNPCWhenBattleEndField, 0)
def AddHideNPCWhenBattleEndField(builder, hideNPCWhenBattleEndField):
    return GroundExcelAddHideNPCWhenBattleEndField(builder, hideNPCWhenBattleEndField)
def GroundExcelAddCoverPointOffField(builder, coverPointOffField): builder.PrependBoolSlot(50, coverPointOffField, 0)
def AddCoverPointOffField(builder, coverPointOffField):
    return GroundExcelAddCoverPointOffField(builder, coverPointOffField)
def GroundExcelAddUIHpScaleField(builder, uIHpScaleField): builder.PrependFloat32Slot(51, uIHpScaleField, 0.0)
def AddUIHpScaleField(builder, uIHpScaleField):
    return GroundExcelAddUIHpScaleField(builder, uIHpScaleField)
def GroundExcelAddUIEmojiScaleField(builder, uIEmojiScaleField): builder.PrependFloat32Slot(52, uIEmojiScaleField, 0.0)
def AddUIEmojiScaleField(builder, uIEmojiScaleField):
    return GroundExcelAddUIEmojiScaleField(builder, uIEmojiScaleField)
def GroundExcelAddUISkillMainLogScaleField(builder, uISkillMainLogScaleField): builder.PrependFloat32Slot(53, uISkillMainLogScaleField, 0.0)
def AddUISkillMainLogScaleField(builder, uISkillMainLogScaleField):
    return GroundExcelAddUISkillMainLogScaleField(builder, uISkillMainLogScaleField)
def GroundExcelAddEffectCountLimitField(builder, effectCountLimitField): builder.PrependInt32Slot(54, effectCountLimitField, 0)
def AddEffectCountLimitField(builder, effectCountLimitField):
    return GroundExcelAddEffectCountLimitField(builder, effectCountLimitField)
def GroundExcelAddCarrierSkillGroupIdField(builder, carrierSkillGroupIdField): builder.PrependInt32Slot(55, carrierSkillGroupIdField, 0)
def AddCarrierSkillGroupIdField(builder, carrierSkillGroupIdField):
    return GroundExcelAddCarrierSkillGroupIdField(builder, carrierSkillGroupIdField)
def GroundExcelAddAllyPassiveSkillIdField(builder, allyPassiveSkillIdField): builder.PrependUOffsetTRelativeSlot(56, flatbuffers.number_types.UOffsetTFlags.py_type(allyPassiveSkillIdField), 0)
def AddAllyPassiveSkillIdField(builder, allyPassiveSkillIdField):
    return GroundExcelAddAllyPassiveSkillIdField(builder, allyPassiveSkillIdField)
def GroundExcelStartAllyPassiveSkillIdFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartAllyPassiveSkillIdFieldVector(builder, numElems):
    return GroundExcelStartAllyPassiveSkillIdFieldVector(builder, numElems)
def GroundExcelAddAllyPassiveSkillLevelField(builder, allyPassiveSkillLevelField): builder.PrependUOffsetTRelativeSlot(57, flatbuffers.number_types.UOffsetTFlags.py_type(allyPassiveSkillLevelField), 0)
def AddAllyPassiveSkillLevelField(builder, allyPassiveSkillLevelField):
    return GroundExcelAddAllyPassiveSkillLevelField(builder, allyPassiveSkillLevelField)
def GroundExcelStartAllyPassiveSkillLevelFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartAllyPassiveSkillLevelFieldVector(builder, numElems):
    return GroundExcelStartAllyPassiveSkillLevelFieldVector(builder, numElems)
def GroundExcelAddEnemyPassiveSkillIdField(builder, enemyPassiveSkillIdField): builder.PrependUOffsetTRelativeSlot(58, flatbuffers.number_types.UOffsetTFlags.py_type(enemyPassiveSkillIdField), 0)
def AddEnemyPassiveSkillIdField(builder, enemyPassiveSkillIdField):
    return GroundExcelAddEnemyPassiveSkillIdField(builder, enemyPassiveSkillIdField)
def GroundExcelStartEnemyPassiveSkillIdFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartEnemyPassiveSkillIdFieldVector(builder, numElems):
    return GroundExcelStartEnemyPassiveSkillIdFieldVector(builder, numElems)
def GroundExcelAddEnemyPassiveSkillLevelField(builder, enemyPassiveSkillLevelField): builder.PrependUOffsetTRelativeSlot(59, flatbuffers.number_types.UOffsetTFlags.py_type(enemyPassiveSkillLevelField), 0)
def AddEnemyPassiveSkillLevelField(builder, enemyPassiveSkillLevelField):
    return GroundExcelAddEnemyPassiveSkillLevelField(builder, enemyPassiveSkillLevelField)
def GroundExcelStartEnemyPassiveSkillLevelFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartEnemyPassiveSkillLevelFieldVector(builder, numElems):
    return GroundExcelStartEnemyPassiveSkillLevelFieldVector(builder, numElems)
def GroundExcelEnd(builder): return builder.EndObject()
def End(builder):
    return GroundExcelEnd(builder)