# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GuideMissionSeasonExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GuideMissionSeasonExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGuideMissionSeasonExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GuideMissionSeasonExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GuideMissionSeasonExcel
    def IdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GuideMissionSeasonExcel
    def TitleLocalizeCodeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionSeasonExcel
    def PermanentInfomationLocalizeCodeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionSeasonExcel
    def InfomationLocalizeCodeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionSeasonExcel
    def TargetGroupField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GuideMissionSeasonExcel
    def EnabledField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GuideMissionSeasonExcel
    def BannerOpenDateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionSeasonExcel
    def StartDateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionSeasonExcel
    def StartableEndDateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionSeasonExcel
    def EndDateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionSeasonExcel
    def CloseBannerAfterCompletionField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GuideMissionSeasonExcel
    def MaximumLoginCountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GuideMissionSeasonExcel
    def ExpiryDateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GuideMissionSeasonExcel
    def IconOrderField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GuideMissionSeasonExcel
    def SpineCharacterIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GuideMissionSeasonExcel
    def RequirementParcelImageField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionSeasonExcel
    def RewardImageField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionSeasonExcel
    def LobbyBannerImageField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionSeasonExcel
    def BackgroundImageField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionSeasonExcel
    def TitleImageField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GuideMissionSeasonExcel
    def RequirementParcelTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GuideMissionSeasonExcel
    def RequirementParcelIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GuideMissionSeasonExcel
    def RequirementParcelAmountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GuideMissionSeasonExcel
    def TabTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # GuideMissionSeasonExcel
    def IsPermanentField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # GuideMissionSeasonExcel
    def PreSeasonIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def GuideMissionSeasonExcelStart(builder): builder.StartObject(26)
def Start(builder):
    return GuideMissionSeasonExcelStart(builder)
def GuideMissionSeasonExcelAddIdField(builder, idField): builder.PrependInt32Slot(0, idField, 0)
def AddIdField(builder, idField):
    return GuideMissionSeasonExcelAddIdField(builder, idField)
def GuideMissionSeasonExcelAddTitleLocalizeCodeField(builder, titleLocalizeCodeField): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(titleLocalizeCodeField), 0)
def AddTitleLocalizeCodeField(builder, titleLocalizeCodeField):
    return GuideMissionSeasonExcelAddTitleLocalizeCodeField(builder, titleLocalizeCodeField)
def GuideMissionSeasonExcelAddPermanentInfomationLocalizeCodeField(builder, permanentInfomationLocalizeCodeField): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(permanentInfomationLocalizeCodeField), 0)
def AddPermanentInfomationLocalizeCodeField(builder, permanentInfomationLocalizeCodeField):
    return GuideMissionSeasonExcelAddPermanentInfomationLocalizeCodeField(builder, permanentInfomationLocalizeCodeField)
def GuideMissionSeasonExcelAddInfomationLocalizeCodeField(builder, infomationLocalizeCodeField): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(infomationLocalizeCodeField), 0)
def AddInfomationLocalizeCodeField(builder, infomationLocalizeCodeField):
    return GuideMissionSeasonExcelAddInfomationLocalizeCodeField(builder, infomationLocalizeCodeField)
def GuideMissionSeasonExcelAddTargetGroupField(builder, targetGroupField): builder.PrependInt32Slot(4, targetGroupField, 0)
def AddTargetGroupField(builder, targetGroupField):
    return GuideMissionSeasonExcelAddTargetGroupField(builder, targetGroupField)
def GuideMissionSeasonExcelAddEnabledField(builder, enabledField): builder.PrependBoolSlot(5, enabledField, 0)
def AddEnabledField(builder, enabledField):
    return GuideMissionSeasonExcelAddEnabledField(builder, enabledField)
def GuideMissionSeasonExcelAddBannerOpenDateField(builder, bannerOpenDateField): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(bannerOpenDateField), 0)
def AddBannerOpenDateField(builder, bannerOpenDateField):
    return GuideMissionSeasonExcelAddBannerOpenDateField(builder, bannerOpenDateField)
def GuideMissionSeasonExcelAddStartDateField(builder, startDateField): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(startDateField), 0)
def AddStartDateField(builder, startDateField):
    return GuideMissionSeasonExcelAddStartDateField(builder, startDateField)
def GuideMissionSeasonExcelAddStartableEndDateField(builder, startableEndDateField): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(startableEndDateField), 0)
def AddStartableEndDateField(builder, startableEndDateField):
    return GuideMissionSeasonExcelAddStartableEndDateField(builder, startableEndDateField)
def GuideMissionSeasonExcelAddEndDateField(builder, endDateField): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(endDateField), 0)
def AddEndDateField(builder, endDateField):
    return GuideMissionSeasonExcelAddEndDateField(builder, endDateField)
def GuideMissionSeasonExcelAddCloseBannerAfterCompletionField(builder, closeBannerAfterCompletionField): builder.PrependBoolSlot(10, closeBannerAfterCompletionField, 0)
def AddCloseBannerAfterCompletionField(builder, closeBannerAfterCompletionField):
    return GuideMissionSeasonExcelAddCloseBannerAfterCompletionField(builder, closeBannerAfterCompletionField)
def GuideMissionSeasonExcelAddMaximumLoginCountField(builder, maximumLoginCountField): builder.PrependInt32Slot(11, maximumLoginCountField, 0)
def AddMaximumLoginCountField(builder, maximumLoginCountField):
    return GuideMissionSeasonExcelAddMaximumLoginCountField(builder, maximumLoginCountField)
def GuideMissionSeasonExcelAddExpiryDateField(builder, expiryDateField): builder.PrependInt32Slot(12, expiryDateField, 0)
def AddExpiryDateField(builder, expiryDateField):
    return GuideMissionSeasonExcelAddExpiryDateField(builder, expiryDateField)
def GuideMissionSeasonExcelAddIconOrderField(builder, iconOrderField): builder.PrependInt32Slot(13, iconOrderField, 0)
def AddIconOrderField(builder, iconOrderField):
    return GuideMissionSeasonExcelAddIconOrderField(builder, iconOrderField)
def GuideMissionSeasonExcelAddSpineCharacterIdField(builder, spineCharacterIdField): builder.PrependInt32Slot(14, spineCharacterIdField, 0)
def AddSpineCharacterIdField(builder, spineCharacterIdField):
    return GuideMissionSeasonExcelAddSpineCharacterIdField(builder, spineCharacterIdField)
def GuideMissionSeasonExcelAddRequirementParcelImageField(builder, requirementParcelImageField): builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(requirementParcelImageField), 0)
def AddRequirementParcelImageField(builder, requirementParcelImageField):
    return GuideMissionSeasonExcelAddRequirementParcelImageField(builder, requirementParcelImageField)
def GuideMissionSeasonExcelAddRewardImageField(builder, rewardImageField): builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(rewardImageField), 0)
def AddRewardImageField(builder, rewardImageField):
    return GuideMissionSeasonExcelAddRewardImageField(builder, rewardImageField)
def GuideMissionSeasonExcelAddLobbyBannerImageField(builder, lobbyBannerImageField): builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(lobbyBannerImageField), 0)
def AddLobbyBannerImageField(builder, lobbyBannerImageField):
    return GuideMissionSeasonExcelAddLobbyBannerImageField(builder, lobbyBannerImageField)
def GuideMissionSeasonExcelAddBackgroundImageField(builder, backgroundImageField): builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(backgroundImageField), 0)
def AddBackgroundImageField(builder, backgroundImageField):
    return GuideMissionSeasonExcelAddBackgroundImageField(builder, backgroundImageField)
def GuideMissionSeasonExcelAddTitleImageField(builder, titleImageField): builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(titleImageField), 0)
def AddTitleImageField(builder, titleImageField):
    return GuideMissionSeasonExcelAddTitleImageField(builder, titleImageField)
def GuideMissionSeasonExcelAddRequirementParcelTypeField(builder, requirementParcelTypeField): builder.PrependInt32Slot(20, requirementParcelTypeField, 0)
def AddRequirementParcelTypeField(builder, requirementParcelTypeField):
    return GuideMissionSeasonExcelAddRequirementParcelTypeField(builder, requirementParcelTypeField)
def GuideMissionSeasonExcelAddRequirementParcelIdField(builder, requirementParcelIdField): builder.PrependInt32Slot(21, requirementParcelIdField, 0)
def AddRequirementParcelIdField(builder, requirementParcelIdField):
    return GuideMissionSeasonExcelAddRequirementParcelIdField(builder, requirementParcelIdField)
def GuideMissionSeasonExcelAddRequirementParcelAmountField(builder, requirementParcelAmountField): builder.PrependInt32Slot(22, requirementParcelAmountField, 0)
def AddRequirementParcelAmountField(builder, requirementParcelAmountField):
    return GuideMissionSeasonExcelAddRequirementParcelAmountField(builder, requirementParcelAmountField)
def GuideMissionSeasonExcelAddTabTypeField(builder, tabTypeField): builder.PrependInt32Slot(23, tabTypeField, 0)
def AddTabTypeField(builder, tabTypeField):
    return GuideMissionSeasonExcelAddTabTypeField(builder, tabTypeField)
def GuideMissionSeasonExcelAddIsPermanentField(builder, isPermanentField): builder.PrependBoolSlot(24, isPermanentField, 0)
def AddIsPermanentField(builder, isPermanentField):
    return GuideMissionSeasonExcelAddIsPermanentField(builder, isPermanentField)
def GuideMissionSeasonExcelAddPreSeasonIdField(builder, preSeasonIdField): builder.PrependInt32Slot(25, preSeasonIdField, 0)
def AddPreSeasonIdField(builder, preSeasonIdField):
    return GuideMissionSeasonExcelAddPreSeasonIdField(builder, preSeasonIdField)
def GuideMissionSeasonExcelEnd(builder): return builder.EndObject()
def End(builder):
    return GuideMissionSeasonExcelEnd(builder)