# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IdCardBackgroundExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IdCardBackgroundExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIdCardBackgroundExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IdCardBackgroundExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IdCardBackgroundExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # IdCardBackgroundExcel
    def Rarity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # IdCardBackgroundExcel
    def DisplayOrder(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # IdCardBackgroundExcel
    def CollectionVisible(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # IdCardBackgroundExcel
    def IsDefault(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # IdCardBackgroundExcel
    def BgPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IdCardBackgroundExcel
    def LocalizeEtcId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # IdCardBackgroundExcel
    def Icon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def IdCardBackgroundExcelStart(builder): builder.StartObject(8)
def Start(builder):
    return IdCardBackgroundExcelStart(builder)
def IdCardBackgroundExcelAddId(builder, id): builder.PrependInt32Slot(0, id, 0)
def AddId(builder, id):
    return IdCardBackgroundExcelAddId(builder, id)
def IdCardBackgroundExcelAddRarity(builder, rarity): builder.PrependInt32Slot(1, rarity, 0)
def AddRarity(builder, rarity):
    return IdCardBackgroundExcelAddRarity(builder, rarity)
def IdCardBackgroundExcelAddDisplayOrder(builder, displayOrder): builder.PrependInt32Slot(2, displayOrder, 0)
def AddDisplayOrder(builder, displayOrder):
    return IdCardBackgroundExcelAddDisplayOrder(builder, displayOrder)
def IdCardBackgroundExcelAddCollectionVisible(builder, collectionVisible): builder.PrependBoolSlot(3, collectionVisible, 0)
def AddCollectionVisible(builder, collectionVisible):
    return IdCardBackgroundExcelAddCollectionVisible(builder, collectionVisible)
def IdCardBackgroundExcelAddIsDefault(builder, isDefault): builder.PrependBoolSlot(4, isDefault, 0)
def AddIsDefault(builder, isDefault):
    return IdCardBackgroundExcelAddIsDefault(builder, isDefault)
def IdCardBackgroundExcelAddBgPath(builder, bgPath): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(bgPath), 0)
def AddBgPath(builder, bgPath):
    return IdCardBackgroundExcelAddBgPath(builder, bgPath)
def IdCardBackgroundExcelAddLocalizeEtcId(builder, localizeEtcId): builder.PrependUint32Slot(6, localizeEtcId, 0)
def AddLocalizeEtcId(builder, localizeEtcId):
    return IdCardBackgroundExcelAddLocalizeEtcId(builder, localizeEtcId)
def IdCardBackgroundExcelAddIcon(builder, icon): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(icon), 0)
def AddIcon(builder, icon):
    return IdCardBackgroundExcelAddIcon(builder, icon)
def IdCardBackgroundExcelEnd(builder): return builder.EndObject()
def End(builder):
    return IdCardBackgroundExcelEnd(builder)