# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InteractiveWorldRaidCarrierMapExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InteractiveWorldRaidCarrierMapExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInteractiveWorldRaidCarrierMapExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InteractiveWorldRaidCarrierMapExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InteractiveWorldRaidCarrierMapExcel
    def IdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def ConditionIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def WorldRaidSeasonIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def WorldRaidPhaseIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def ReplaySeasonGroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def ReplaySeasonOriginalPhaseIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def RecentClearBossGroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def RecentClearEventStageIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def ChangeTargetField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def PriorityField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def ArtLevelPathField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InteractiveWorldRaidCarrierMapExcel
    def DesignLevelPathField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InteractiveWorldRaidCarrierMapExcel
    def BridgeBGMField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def HangarBGMField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def LobbyBGMField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def WorldMapBGMField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def InformationGroupIdWorldMapField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def InformationGroupIdUCPopupField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def InformationGroupIdBridgeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def InformationGroupIdHangarField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidCarrierMapExcel
    def InformationGroupIdLobbyField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def InteractiveWorldRaidCarrierMapExcelStart(builder): builder.StartObject(21)
def Start(builder):
    return InteractiveWorldRaidCarrierMapExcelStart(builder)
def InteractiveWorldRaidCarrierMapExcelAddIdField(builder, idField): builder.PrependInt32Slot(0, idField, 0)
def AddIdField(builder, idField):
    return InteractiveWorldRaidCarrierMapExcelAddIdField(builder, idField)
def InteractiveWorldRaidCarrierMapExcelAddConditionIdField(builder, conditionIdField): builder.PrependInt32Slot(1, conditionIdField, 0)
def AddConditionIdField(builder, conditionIdField):
    return InteractiveWorldRaidCarrierMapExcelAddConditionIdField(builder, conditionIdField)
def InteractiveWorldRaidCarrierMapExcelAddWorldRaidSeasonIdField(builder, worldRaidSeasonIdField): builder.PrependInt32Slot(2, worldRaidSeasonIdField, 0)
def AddWorldRaidSeasonIdField(builder, worldRaidSeasonIdField):
    return InteractiveWorldRaidCarrierMapExcelAddWorldRaidSeasonIdField(builder, worldRaidSeasonIdField)
def InteractiveWorldRaidCarrierMapExcelAddWorldRaidPhaseIdField(builder, worldRaidPhaseIdField): builder.PrependInt32Slot(3, worldRaidPhaseIdField, 0)
def AddWorldRaidPhaseIdField(builder, worldRaidPhaseIdField):
    return InteractiveWorldRaidCarrierMapExcelAddWorldRaidPhaseIdField(builder, worldRaidPhaseIdField)
def InteractiveWorldRaidCarrierMapExcelAddReplaySeasonGroupIdField(builder, replaySeasonGroupIdField): builder.PrependInt32Slot(4, replaySeasonGroupIdField, 0)
def AddReplaySeasonGroupIdField(builder, replaySeasonGroupIdField):
    return InteractiveWorldRaidCarrierMapExcelAddReplaySeasonGroupIdField(builder, replaySeasonGroupIdField)
def InteractiveWorldRaidCarrierMapExcelAddReplaySeasonOriginalPhaseIdField(builder, replaySeasonOriginalPhaseIdField): builder.PrependInt32Slot(5, replaySeasonOriginalPhaseIdField, 0)
def AddReplaySeasonOriginalPhaseIdField(builder, replaySeasonOriginalPhaseIdField):
    return InteractiveWorldRaidCarrierMapExcelAddReplaySeasonOriginalPhaseIdField(builder, replaySeasonOriginalPhaseIdField)
def InteractiveWorldRaidCarrierMapExcelAddRecentClearBossGroupIdField(builder, recentClearBossGroupIdField): builder.PrependInt32Slot(6, recentClearBossGroupIdField, 0)
def AddRecentClearBossGroupIdField(builder, recentClearBossGroupIdField):
    return InteractiveWorldRaidCarrierMapExcelAddRecentClearBossGroupIdField(builder, recentClearBossGroupIdField)
def InteractiveWorldRaidCarrierMapExcelAddRecentClearEventStageIdField(builder, recentClearEventStageIdField): builder.PrependInt32Slot(7, recentClearEventStageIdField, 0)
def AddRecentClearEventStageIdField(builder, recentClearEventStageIdField):
    return InteractiveWorldRaidCarrierMapExcelAddRecentClearEventStageIdField(builder, recentClearEventStageIdField)
def InteractiveWorldRaidCarrierMapExcelAddChangeTargetField(builder, changeTargetField): builder.PrependInt32Slot(8, changeTargetField, 0)
def AddChangeTargetField(builder, changeTargetField):
    return InteractiveWorldRaidCarrierMapExcelAddChangeTargetField(builder, changeTargetField)
def InteractiveWorldRaidCarrierMapExcelAddPriorityField(builder, priorityField): builder.PrependInt32Slot(9, priorityField, 0)
def AddPriorityField(builder, priorityField):
    return InteractiveWorldRaidCarrierMapExcelAddPriorityField(builder, priorityField)
def InteractiveWorldRaidCarrierMapExcelAddArtLevelPathField(builder, artLevelPathField): builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(artLevelPathField), 0)
def AddArtLevelPathField(builder, artLevelPathField):
    return InteractiveWorldRaidCarrierMapExcelAddArtLevelPathField(builder, artLevelPathField)
def InteractiveWorldRaidCarrierMapExcelAddDesignLevelPathField(builder, designLevelPathField): builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(designLevelPathField), 0)
def AddDesignLevelPathField(builder, designLevelPathField):
    return InteractiveWorldRaidCarrierMapExcelAddDesignLevelPathField(builder, designLevelPathField)
def InteractiveWorldRaidCarrierMapExcelAddBridgeBGMField(builder, bridgeBGMField): builder.PrependInt32Slot(12, bridgeBGMField, 0)
def AddBridgeBGMField(builder, bridgeBGMField):
    return InteractiveWorldRaidCarrierMapExcelAddBridgeBGMField(builder, bridgeBGMField)
def InteractiveWorldRaidCarrierMapExcelAddHangarBGMField(builder, hangarBGMField): builder.PrependInt32Slot(13, hangarBGMField, 0)
def AddHangarBGMField(builder, hangarBGMField):
    return InteractiveWorldRaidCarrierMapExcelAddHangarBGMField(builder, hangarBGMField)
def InteractiveWorldRaidCarrierMapExcelAddLobbyBGMField(builder, lobbyBGMField): builder.PrependInt32Slot(14, lobbyBGMField, 0)
def AddLobbyBGMField(builder, lobbyBGMField):
    return InteractiveWorldRaidCarrierMapExcelAddLobbyBGMField(builder, lobbyBGMField)
def InteractiveWorldRaidCarrierMapExcelAddWorldMapBGMField(builder, worldMapBGMField): builder.PrependInt32Slot(15, worldMapBGMField, 0)
def AddWorldMapBGMField(builder, worldMapBGMField):
    return InteractiveWorldRaidCarrierMapExcelAddWorldMapBGMField(builder, worldMapBGMField)
def InteractiveWorldRaidCarrierMapExcelAddInformationGroupIdWorldMapField(builder, informationGroupIdWorldMapField): builder.PrependInt32Slot(16, informationGroupIdWorldMapField, 0)
def AddInformationGroupIdWorldMapField(builder, informationGroupIdWorldMapField):
    return InteractiveWorldRaidCarrierMapExcelAddInformationGroupIdWorldMapField(builder, informationGroupIdWorldMapField)
def InteractiveWorldRaidCarrierMapExcelAddInformationGroupIdUCPopupField(builder, informationGroupIdUCPopupField): builder.PrependInt32Slot(17, informationGroupIdUCPopupField, 0)
def AddInformationGroupIdUCPopupField(builder, informationGroupIdUCPopupField):
    return InteractiveWorldRaidCarrierMapExcelAddInformationGroupIdUCPopupField(builder, informationGroupIdUCPopupField)
def InteractiveWorldRaidCarrierMapExcelAddInformationGroupIdBridgeField(builder, informationGroupIdBridgeField): builder.PrependInt32Slot(18, informationGroupIdBridgeField, 0)
def AddInformationGroupIdBridgeField(builder, informationGroupIdBridgeField):
    return InteractiveWorldRaidCarrierMapExcelAddInformationGroupIdBridgeField(builder, informationGroupIdBridgeField)
def InteractiveWorldRaidCarrierMapExcelAddInformationGroupIdHangarField(builder, informationGroupIdHangarField): builder.PrependInt32Slot(19, informationGroupIdHangarField, 0)
def AddInformationGroupIdHangarField(builder, informationGroupIdHangarField):
    return InteractiveWorldRaidCarrierMapExcelAddInformationGroupIdHangarField(builder, informationGroupIdHangarField)
def InteractiveWorldRaidCarrierMapExcelAddInformationGroupIdLobbyField(builder, informationGroupIdLobbyField): builder.PrependInt32Slot(20, informationGroupIdLobbyField, 0)
def AddInformationGroupIdLobbyField(builder, informationGroupIdLobbyField):
    return InteractiveWorldRaidCarrierMapExcelAddInformationGroupIdLobbyField(builder, informationGroupIdLobbyField)
def InteractiveWorldRaidCarrierMapExcelEnd(builder): return builder.EndObject()
def End(builder):
    return InteractiveWorldRaidCarrierMapExcelEnd(builder)