# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InteractiveWorldRaidStageExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InteractiveWorldRaidStageExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInteractiveWorldRaidStageExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InteractiveWorldRaidStageExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InteractiveWorldRaidStageExcel
    def IdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def UseBossIndexField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # InteractiveWorldRaidStageExcel
    def UseBossAIPhaseSyncField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # InteractiveWorldRaidStageExcel
    def WorldRaidBossGroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def PortraitPathField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InteractiveWorldRaidStageExcel
    def BGPathField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InteractiveWorldRaidStageExcel
    def RaidSkillDescriptionListIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def RaidCharacterIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def BossCharacterIdField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # InteractiveWorldRaidStageExcel
    def BossCharacterIdFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # InteractiveWorldRaidStageExcel
    def BossCharacterIdFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InteractiveWorldRaidStageExcel
    def BossCharacterIdFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # InteractiveWorldRaidStageExcel
    def AssistCharacterLimitCountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def WorldRaidDifficultyField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def DifficultyOpenConditionField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # InteractiveWorldRaidStageExcel
    def RaidEnterAmountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def ReEnterAmountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def BattleDurationField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def GroundIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def RaidBattleEndRewardGroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def RaidRewardGroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def BattleReadyTimelinePathField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # InteractiveWorldRaidStageExcel
    def BattleReadyTimelinePathFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InteractiveWorldRaidStageExcel
    def BattleReadyTimelinePathFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        return o == 0

    # InteractiveWorldRaidStageExcel
    def BattleReadyTimelinePhaseStartField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # InteractiveWorldRaidStageExcel
    def BattleReadyTimelinePhaseStartFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # InteractiveWorldRaidStageExcel
    def BattleReadyTimelinePhaseStartFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InteractiveWorldRaidStageExcel
    def BattleReadyTimelinePhaseStartFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        return o == 0

    # InteractiveWorldRaidStageExcel
    def BattleReadyTimelinePhaseEndField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # InteractiveWorldRaidStageExcel
    def BattleReadyTimelinePhaseEndFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # InteractiveWorldRaidStageExcel
    def BattleReadyTimelinePhaseEndFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InteractiveWorldRaidStageExcel
    def BattleReadyTimelinePhaseEndFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        return o == 0

    # InteractiveWorldRaidStageExcel
    def VictoryTimelinePathField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InteractiveWorldRaidStageExcel
    def PhaseChangeTimelinePathField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InteractiveWorldRaidStageExcel
    def TimeLinePhaseField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def EnterScenarioKeyField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def ClearScenarioKeyField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def UseFixedEchelonField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # InteractiveWorldRaidStageExcel
    def FixedEchelonIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def IsRaidScenarioBattleField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # InteractiveWorldRaidStageExcel
    def ShowSkillCardField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # InteractiveWorldRaidStageExcel
    def BossBGInfoKeyField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def DamageToWorldBossField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # InteractiveWorldRaidStageExcel
    def AllyPassiveSkillField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # InteractiveWorldRaidStageExcel
    def AllyPassiveSkillFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InteractiveWorldRaidStageExcel
    def AllyPassiveSkillFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        return o == 0

    # InteractiveWorldRaidStageExcel
    def AllyPassiveSkillLevelField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # InteractiveWorldRaidStageExcel
    def AllyPassiveSkillLevelFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # InteractiveWorldRaidStageExcel
    def AllyPassiveSkillLevelFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InteractiveWorldRaidStageExcel
    def AllyPassiveSkillLevelFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        return o == 0

    # InteractiveWorldRaidStageExcel
    def AllyPassiveSkillRemoveConditionField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # InteractiveWorldRaidStageExcel
    def AllyPassiveSkillRemoveConditionFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # InteractiveWorldRaidStageExcel
    def AllyPassiveSkillRemoveConditionFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InteractiveWorldRaidStageExcel
    def AllyPassiveSkillRemoveConditionFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        return o == 0

    # InteractiveWorldRaidStageExcel
    def EnemyPassiveSkillField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # InteractiveWorldRaidStageExcel
    def EnemyPassiveSkillFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InteractiveWorldRaidStageExcel
    def EnemyPassiveSkillFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        return o == 0

    # InteractiveWorldRaidStageExcel
    def EnemyPassiveSkillLevelField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # InteractiveWorldRaidStageExcel
    def EnemyPassiveSkillLevelFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # InteractiveWorldRaidStageExcel
    def EnemyPassiveSkillLevelFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InteractiveWorldRaidStageExcel
    def EnemyPassiveSkillLevelFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        return o == 0

    # InteractiveWorldRaidStageExcel
    def EnemyPassiveSkillRemoveConditionField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # InteractiveWorldRaidStageExcel
    def EnemyPassiveSkillRemoveConditionFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # InteractiveWorldRaidStageExcel
    def EnemyPassiveSkillRemoveConditionFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InteractiveWorldRaidStageExcel
    def EnemyPassiveSkillRemoveConditionFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        return o == 0

    # InteractiveWorldRaidStageExcel
    def SaveCurrentLocalBossHPField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(80))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # InteractiveWorldRaidStageExcel
    def EchelonExtensionTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(82))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def InteractiveWorldRaidStageExcelStart(builder): builder.StartObject(40)
def Start(builder):
    return InteractiveWorldRaidStageExcelStart(builder)
def InteractiveWorldRaidStageExcelAddIdField(builder, idField): builder.PrependInt32Slot(0, idField, 0)
def AddIdField(builder, idField):
    return InteractiveWorldRaidStageExcelAddIdField(builder, idField)
def InteractiveWorldRaidStageExcelAddUseBossIndexField(builder, useBossIndexField): builder.PrependBoolSlot(1, useBossIndexField, 0)
def AddUseBossIndexField(builder, useBossIndexField):
    return InteractiveWorldRaidStageExcelAddUseBossIndexField(builder, useBossIndexField)
def InteractiveWorldRaidStageExcelAddUseBossAIPhaseSyncField(builder, useBossAIPhaseSyncField): builder.PrependBoolSlot(2, useBossAIPhaseSyncField, 0)
def AddUseBossAIPhaseSyncField(builder, useBossAIPhaseSyncField):
    return InteractiveWorldRaidStageExcelAddUseBossAIPhaseSyncField(builder, useBossAIPhaseSyncField)
def InteractiveWorldRaidStageExcelAddWorldRaidBossGroupIdField(builder, worldRaidBossGroupIdField): builder.PrependInt32Slot(3, worldRaidBossGroupIdField, 0)
def AddWorldRaidBossGroupIdField(builder, worldRaidBossGroupIdField):
    return InteractiveWorldRaidStageExcelAddWorldRaidBossGroupIdField(builder, worldRaidBossGroupIdField)
def InteractiveWorldRaidStageExcelAddPortraitPathField(builder, portraitPathField): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(portraitPathField), 0)
def AddPortraitPathField(builder, portraitPathField):
    return InteractiveWorldRaidStageExcelAddPortraitPathField(builder, portraitPathField)
def InteractiveWorldRaidStageExcelAddBGPathField(builder, bGPathField): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(bGPathField), 0)
def AddBGPathField(builder, bGPathField):
    return InteractiveWorldRaidStageExcelAddBGPathField(builder, bGPathField)
def InteractiveWorldRaidStageExcelAddRaidSkillDescriptionListIdField(builder, raidSkillDescriptionListIdField): builder.PrependInt32Slot(6, raidSkillDescriptionListIdField, 0)
def AddRaidSkillDescriptionListIdField(builder, raidSkillDescriptionListIdField):
    return InteractiveWorldRaidStageExcelAddRaidSkillDescriptionListIdField(builder, raidSkillDescriptionListIdField)
def InteractiveWorldRaidStageExcelAddRaidCharacterIdField(builder, raidCharacterIdField): builder.PrependInt32Slot(7, raidCharacterIdField, 0)
def AddRaidCharacterIdField(builder, raidCharacterIdField):
    return InteractiveWorldRaidStageExcelAddRaidCharacterIdField(builder, raidCharacterIdField)
def InteractiveWorldRaidStageExcelAddBossCharacterIdField(builder, bossCharacterIdField): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(bossCharacterIdField), 0)
def AddBossCharacterIdField(builder, bossCharacterIdField):
    return InteractiveWorldRaidStageExcelAddBossCharacterIdField(builder, bossCharacterIdField)
def InteractiveWorldRaidStageExcelStartBossCharacterIdFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartBossCharacterIdFieldVector(builder, numElems):
    return InteractiveWorldRaidStageExcelStartBossCharacterIdFieldVector(builder, numElems)
def InteractiveWorldRaidStageExcelAddAssistCharacterLimitCountField(builder, assistCharacterLimitCountField): builder.PrependInt32Slot(9, assistCharacterLimitCountField, 0)
def AddAssistCharacterLimitCountField(builder, assistCharacterLimitCountField):
    return InteractiveWorldRaidStageExcelAddAssistCharacterLimitCountField(builder, assistCharacterLimitCountField)
def InteractiveWorldRaidStageExcelAddWorldRaidDifficultyField(builder, worldRaidDifficultyField): builder.PrependInt32Slot(10, worldRaidDifficultyField, 0)
def AddWorldRaidDifficultyField(builder, worldRaidDifficultyField):
    return InteractiveWorldRaidStageExcelAddWorldRaidDifficultyField(builder, worldRaidDifficultyField)
def InteractiveWorldRaidStageExcelAddDifficultyOpenConditionField(builder, difficultyOpenConditionField): builder.PrependBoolSlot(11, difficultyOpenConditionField, 0)
def AddDifficultyOpenConditionField(builder, difficultyOpenConditionField):
    return InteractiveWorldRaidStageExcelAddDifficultyOpenConditionField(builder, difficultyOpenConditionField)
def InteractiveWorldRaidStageExcelAddRaidEnterAmountField(builder, raidEnterAmountField): builder.PrependInt32Slot(12, raidEnterAmountField, 0)
def AddRaidEnterAmountField(builder, raidEnterAmountField):
    return InteractiveWorldRaidStageExcelAddRaidEnterAmountField(builder, raidEnterAmountField)
def InteractiveWorldRaidStageExcelAddReEnterAmountField(builder, reEnterAmountField): builder.PrependInt32Slot(13, reEnterAmountField, 0)
def AddReEnterAmountField(builder, reEnterAmountField):
    return InteractiveWorldRaidStageExcelAddReEnterAmountField(builder, reEnterAmountField)
def InteractiveWorldRaidStageExcelAddBattleDurationField(builder, battleDurationField): builder.PrependInt32Slot(14, battleDurationField, 0)
def AddBattleDurationField(builder, battleDurationField):
    return InteractiveWorldRaidStageExcelAddBattleDurationField(builder, battleDurationField)
def InteractiveWorldRaidStageExcelAddGroundIdField(builder, groundIdField): builder.PrependInt32Slot(15, groundIdField, 0)
def AddGroundIdField(builder, groundIdField):
    return InteractiveWorldRaidStageExcelAddGroundIdField(builder, groundIdField)
def InteractiveWorldRaidStageExcelAddRaidBattleEndRewardGroupIdField(builder, raidBattleEndRewardGroupIdField): builder.PrependInt32Slot(16, raidBattleEndRewardGroupIdField, 0)
def AddRaidBattleEndRewardGroupIdField(builder, raidBattleEndRewardGroupIdField):
    return InteractiveWorldRaidStageExcelAddRaidBattleEndRewardGroupIdField(builder, raidBattleEndRewardGroupIdField)
def InteractiveWorldRaidStageExcelAddRaidRewardGroupIdField(builder, raidRewardGroupIdField): builder.PrependInt32Slot(17, raidRewardGroupIdField, 0)
def AddRaidRewardGroupIdField(builder, raidRewardGroupIdField):
    return InteractiveWorldRaidStageExcelAddRaidRewardGroupIdField(builder, raidRewardGroupIdField)
def InteractiveWorldRaidStageExcelAddBattleReadyTimelinePathField(builder, battleReadyTimelinePathField): builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(battleReadyTimelinePathField), 0)
def AddBattleReadyTimelinePathField(builder, battleReadyTimelinePathField):
    return InteractiveWorldRaidStageExcelAddBattleReadyTimelinePathField(builder, battleReadyTimelinePathField)
def InteractiveWorldRaidStageExcelStartBattleReadyTimelinePathFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartBattleReadyTimelinePathFieldVector(builder, numElems):
    return InteractiveWorldRaidStageExcelStartBattleReadyTimelinePathFieldVector(builder, numElems)
def InteractiveWorldRaidStageExcelAddBattleReadyTimelinePhaseStartField(builder, battleReadyTimelinePhaseStartField): builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(battleReadyTimelinePhaseStartField), 0)
def AddBattleReadyTimelinePhaseStartField(builder, battleReadyTimelinePhaseStartField):
    return InteractiveWorldRaidStageExcelAddBattleReadyTimelinePhaseStartField(builder, battleReadyTimelinePhaseStartField)
def InteractiveWorldRaidStageExcelStartBattleReadyTimelinePhaseStartFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartBattleReadyTimelinePhaseStartFieldVector(builder, numElems):
    return InteractiveWorldRaidStageExcelStartBattleReadyTimelinePhaseStartFieldVector(builder, numElems)
def InteractiveWorldRaidStageExcelAddBattleReadyTimelinePhaseEndField(builder, battleReadyTimelinePhaseEndField): builder.PrependUOffsetTRelativeSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(battleReadyTimelinePhaseEndField), 0)
def AddBattleReadyTimelinePhaseEndField(builder, battleReadyTimelinePhaseEndField):
    return InteractiveWorldRaidStageExcelAddBattleReadyTimelinePhaseEndField(builder, battleReadyTimelinePhaseEndField)
def InteractiveWorldRaidStageExcelStartBattleReadyTimelinePhaseEndFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartBattleReadyTimelinePhaseEndFieldVector(builder, numElems):
    return InteractiveWorldRaidStageExcelStartBattleReadyTimelinePhaseEndFieldVector(builder, numElems)
def InteractiveWorldRaidStageExcelAddVictoryTimelinePathField(builder, victoryTimelinePathField): builder.PrependUOffsetTRelativeSlot(21, flatbuffers.number_types.UOffsetTFlags.py_type(victoryTimelinePathField), 0)
def AddVictoryTimelinePathField(builder, victoryTimelinePathField):
    return InteractiveWorldRaidStageExcelAddVictoryTimelinePathField(builder, victoryTimelinePathField)
def InteractiveWorldRaidStageExcelAddPhaseChangeTimelinePathField(builder, phaseChangeTimelinePathField): builder.PrependUOffsetTRelativeSlot(22, flatbuffers.number_types.UOffsetTFlags.py_type(phaseChangeTimelinePathField), 0)
def AddPhaseChangeTimelinePathField(builder, phaseChangeTimelinePathField):
    return InteractiveWorldRaidStageExcelAddPhaseChangeTimelinePathField(builder, phaseChangeTimelinePathField)
def InteractiveWorldRaidStageExcelAddTimeLinePhaseField(builder, timeLinePhaseField): builder.PrependInt32Slot(23, timeLinePhaseField, 0)
def AddTimeLinePhaseField(builder, timeLinePhaseField):
    return InteractiveWorldRaidStageExcelAddTimeLinePhaseField(builder, timeLinePhaseField)
def InteractiveWorldRaidStageExcelAddEnterScenarioKeyField(builder, enterScenarioKeyField): builder.PrependInt32Slot(24, enterScenarioKeyField, 0)
def AddEnterScenarioKeyField(builder, enterScenarioKeyField):
    return InteractiveWorldRaidStageExcelAddEnterScenarioKeyField(builder, enterScenarioKeyField)
def InteractiveWorldRaidStageExcelAddClearScenarioKeyField(builder, clearScenarioKeyField): builder.PrependInt32Slot(25, clearScenarioKeyField, 0)
def AddClearScenarioKeyField(builder, clearScenarioKeyField):
    return InteractiveWorldRaidStageExcelAddClearScenarioKeyField(builder, clearScenarioKeyField)
def InteractiveWorldRaidStageExcelAddUseFixedEchelonField(builder, useFixedEchelonField): builder.PrependBoolSlot(26, useFixedEchelonField, 0)
def AddUseFixedEchelonField(builder, useFixedEchelonField):
    return InteractiveWorldRaidStageExcelAddUseFixedEchelonField(builder, useFixedEchelonField)
def InteractiveWorldRaidStageExcelAddFixedEchelonIdField(builder, fixedEchelonIdField): builder.PrependInt32Slot(27, fixedEchelonIdField, 0)
def AddFixedEchelonIdField(builder, fixedEchelonIdField):
    return InteractiveWorldRaidStageExcelAddFixedEchelonIdField(builder, fixedEchelonIdField)
def InteractiveWorldRaidStageExcelAddIsRaidScenarioBattleField(builder, isRaidScenarioBattleField): builder.PrependBoolSlot(28, isRaidScenarioBattleField, 0)
def AddIsRaidScenarioBattleField(builder, isRaidScenarioBattleField):
    return InteractiveWorldRaidStageExcelAddIsRaidScenarioBattleField(builder, isRaidScenarioBattleField)
def InteractiveWorldRaidStageExcelAddShowSkillCardField(builder, showSkillCardField): builder.PrependBoolSlot(29, showSkillCardField, 0)
def AddShowSkillCardField(builder, showSkillCardField):
    return InteractiveWorldRaidStageExcelAddShowSkillCardField(builder, showSkillCardField)
def InteractiveWorldRaidStageExcelAddBossBGInfoKeyField(builder, bossBGInfoKeyField): builder.PrependUint32Slot(30, bossBGInfoKeyField, 0)
def AddBossBGInfoKeyField(builder, bossBGInfoKeyField):
    return InteractiveWorldRaidStageExcelAddBossBGInfoKeyField(builder, bossBGInfoKeyField)
def InteractiveWorldRaidStageExcelAddDamageToWorldBossField(builder, damageToWorldBossField): builder.PrependInt32Slot(31, damageToWorldBossField, 0)
def AddDamageToWorldBossField(builder, damageToWorldBossField):
    return InteractiveWorldRaidStageExcelAddDamageToWorldBossField(builder, damageToWorldBossField)
def InteractiveWorldRaidStageExcelAddAllyPassiveSkillField(builder, allyPassiveSkillField): builder.PrependUOffsetTRelativeSlot(32, flatbuffers.number_types.UOffsetTFlags.py_type(allyPassiveSkillField), 0)
def AddAllyPassiveSkillField(builder, allyPassiveSkillField):
    return InteractiveWorldRaidStageExcelAddAllyPassiveSkillField(builder, allyPassiveSkillField)
def InteractiveWorldRaidStageExcelStartAllyPassiveSkillFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartAllyPassiveSkillFieldVector(builder, numElems):
    return InteractiveWorldRaidStageExcelStartAllyPassiveSkillFieldVector(builder, numElems)
def InteractiveWorldRaidStageExcelAddAllyPassiveSkillLevelField(builder, allyPassiveSkillLevelField): builder.PrependUOffsetTRelativeSlot(33, flatbuffers.number_types.UOffsetTFlags.py_type(allyPassiveSkillLevelField), 0)
def AddAllyPassiveSkillLevelField(builder, allyPassiveSkillLevelField):
    return InteractiveWorldRaidStageExcelAddAllyPassiveSkillLevelField(builder, allyPassiveSkillLevelField)
def InteractiveWorldRaidStageExcelStartAllyPassiveSkillLevelFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartAllyPassiveSkillLevelFieldVector(builder, numElems):
    return InteractiveWorldRaidStageExcelStartAllyPassiveSkillLevelFieldVector(builder, numElems)
def InteractiveWorldRaidStageExcelAddAllyPassiveSkillRemoveConditionField(builder, allyPassiveSkillRemoveConditionField): builder.PrependUOffsetTRelativeSlot(34, flatbuffers.number_types.UOffsetTFlags.py_type(allyPassiveSkillRemoveConditionField), 0)
def AddAllyPassiveSkillRemoveConditionField(builder, allyPassiveSkillRemoveConditionField):
    return InteractiveWorldRaidStageExcelAddAllyPassiveSkillRemoveConditionField(builder, allyPassiveSkillRemoveConditionField)
def InteractiveWorldRaidStageExcelStartAllyPassiveSkillRemoveConditionFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartAllyPassiveSkillRemoveConditionFieldVector(builder, numElems):
    return InteractiveWorldRaidStageExcelStartAllyPassiveSkillRemoveConditionFieldVector(builder, numElems)
def InteractiveWorldRaidStageExcelAddEnemyPassiveSkillField(builder, enemyPassiveSkillField): builder.PrependUOffsetTRelativeSlot(35, flatbuffers.number_types.UOffsetTFlags.py_type(enemyPassiveSkillField), 0)
def AddEnemyPassiveSkillField(builder, enemyPassiveSkillField):
    return InteractiveWorldRaidStageExcelAddEnemyPassiveSkillField(builder, enemyPassiveSkillField)
def InteractiveWorldRaidStageExcelStartEnemyPassiveSkillFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartEnemyPassiveSkillFieldVector(builder, numElems):
    return InteractiveWorldRaidStageExcelStartEnemyPassiveSkillFieldVector(builder, numElems)
def InteractiveWorldRaidStageExcelAddEnemyPassiveSkillLevelField(builder, enemyPassiveSkillLevelField): builder.PrependUOffsetTRelativeSlot(36, flatbuffers.number_types.UOffsetTFlags.py_type(enemyPassiveSkillLevelField), 0)
def AddEnemyPassiveSkillLevelField(builder, enemyPassiveSkillLevelField):
    return InteractiveWorldRaidStageExcelAddEnemyPassiveSkillLevelField(builder, enemyPassiveSkillLevelField)
def InteractiveWorldRaidStageExcelStartEnemyPassiveSkillLevelFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartEnemyPassiveSkillLevelFieldVector(builder, numElems):
    return InteractiveWorldRaidStageExcelStartEnemyPassiveSkillLevelFieldVector(builder, numElems)
def InteractiveWorldRaidStageExcelAddEnemyPassiveSkillRemoveConditionField(builder, enemyPassiveSkillRemoveConditionField): builder.PrependUOffsetTRelativeSlot(37, flatbuffers.number_types.UOffsetTFlags.py_type(enemyPassiveSkillRemoveConditionField), 0)
def AddEnemyPassiveSkillRemoveConditionField(builder, enemyPassiveSkillRemoveConditionField):
    return InteractiveWorldRaidStageExcelAddEnemyPassiveSkillRemoveConditionField(builder, enemyPassiveSkillRemoveConditionField)
def InteractiveWorldRaidStageExcelStartEnemyPassiveSkillRemoveConditionFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartEnemyPassiveSkillRemoveConditionFieldVector(builder, numElems):
    return InteractiveWorldRaidStageExcelStartEnemyPassiveSkillRemoveConditionFieldVector(builder, numElems)
def InteractiveWorldRaidStageExcelAddSaveCurrentLocalBossHPField(builder, saveCurrentLocalBossHPField): builder.PrependBoolSlot(38, saveCurrentLocalBossHPField, 0)
def AddSaveCurrentLocalBossHPField(builder, saveCurrentLocalBossHPField):
    return InteractiveWorldRaidStageExcelAddSaveCurrentLocalBossHPField(builder, saveCurrentLocalBossHPField)
def InteractiveWorldRaidStageExcelAddEchelonExtensionTypeField(builder, echelonExtensionTypeField): builder.PrependInt32Slot(39, echelonExtensionTypeField, 0)
def AddEchelonExtensionTypeField(builder, echelonExtensionTypeField):
    return InteractiveWorldRaidStageExcelAddEchelonExtensionTypeField(builder, echelonExtensionTypeField)
def InteractiveWorldRaidStageExcelEnd(builder): return builder.EndObject()
def End(builder):
    return InteractiveWorldRaidStageExcelEnd(builder)