# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class KeyControllerImageExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KeyControllerImageExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKeyControllerImageExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KeyControllerImageExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KeyControllerImageExcel
    def ControllerKeyCodeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # KeyControllerImageExcel
    def PSIconNameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # KeyControllerImageExcel
    def XBoxIconNameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # KeyControllerImageExcel
    def SteamDeckIconNameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def KeyControllerImageExcelStart(builder): builder.StartObject(4)
def Start(builder):
    return KeyControllerImageExcelStart(builder)
def KeyControllerImageExcelAddControllerKeyCodeField(builder, controllerKeyCodeField): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(controllerKeyCodeField), 0)
def AddControllerKeyCodeField(builder, controllerKeyCodeField):
    return KeyControllerImageExcelAddControllerKeyCodeField(builder, controllerKeyCodeField)
def KeyControllerImageExcelAddPSIconNameField(builder, pSIconNameField): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(pSIconNameField), 0)
def AddPSIconNameField(builder, pSIconNameField):
    return KeyControllerImageExcelAddPSIconNameField(builder, pSIconNameField)
def KeyControllerImageExcelAddXBoxIconNameField(builder, xBoxIconNameField): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(xBoxIconNameField), 0)
def AddXBoxIconNameField(builder, xBoxIconNameField):
    return KeyControllerImageExcelAddXBoxIconNameField(builder, xBoxIconNameField)
def KeyControllerImageExcelAddSteamDeckIconNameField(builder, steamDeckIconNameField): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(steamDeckIconNameField), 0)
def AddSteamDeckIconNameField(builder, steamDeckIconNameField):
    return KeyControllerImageExcelAddSteamDeckIconNameField(builder, steamDeckIconNameField)
def KeyControllerImageExcelEnd(builder): return builder.EndObject()
def End(builder):
    return KeyControllerImageExcelEnd(builder)