# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MiniGameMissionExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MiniGameMissionExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMiniGameMissionExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MiniGameMissionExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MiniGameMissionExcel
    def IdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MiniGameMissionExcel
    def EventContentIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MiniGameMissionExcel
    def GroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MiniGameMissionExcel
    def GroupNameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MiniGameMissionExcel
    def CategoryField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MiniGameMissionExcel
    def DescriptionField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MiniGameMissionExcel
    def ResetTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MiniGameMissionExcel
    def ToastDisplayTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MiniGameMissionExcel
    def ToastImagePathField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MiniGameMissionExcel
    def ViewFlagField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MiniGameMissionExcel
    def DisplayOrderField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MiniGameMissionExcel
    def PreMissionIdField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MiniGameMissionExcel
    def PreMissionIdFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # MiniGameMissionExcel
    def PreMissionIdFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MiniGameMissionExcel
    def PreMissionIdFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # MiniGameMissionExcel
    def TargetGroupField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MiniGameMissionExcel
    def AccountLevelField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MiniGameMissionExcel
    def ShortcutUIField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # MiniGameMissionExcel
    def ShortcutUIFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MiniGameMissionExcel
    def ShortcutUIFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        return o == 0

    # MiniGameMissionExcel
    def CompleteConditionTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MiniGameMissionExcel
    def IsCompleteExtensionTimeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MiniGameMissionExcel
    def CompleteConditionCountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MiniGameMissionExcel
    def CompleteConditionParameterField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MiniGameMissionExcel
    def CompleteConditionParameterFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # MiniGameMissionExcel
    def CompleteConditionParameterFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MiniGameMissionExcel
    def CompleteConditionParameterFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        return o == 0

    # MiniGameMissionExcel
    def CompleteConditionParameterTagField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MiniGameMissionExcel
    def CompleteConditionParameterTagFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # MiniGameMissionExcel
    def CompleteConditionParameterTagFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MiniGameMissionExcel
    def CompleteConditionParameterTagFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        return o == 0

    # MiniGameMissionExcel
    def RewardIconField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MiniGameMissionExcel
    def CompleteConditionMissionIdField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MiniGameMissionExcel
    def CompleteConditionMissionIdFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # MiniGameMissionExcel
    def CompleteConditionMissionIdFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MiniGameMissionExcel
    def CompleteConditionMissionIdFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        return o == 0

    # MiniGameMissionExcel
    def CompleteConditionMissionCountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MiniGameMissionExcel
    def MissionRewardParcelTypeField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MiniGameMissionExcel
    def MissionRewardParcelTypeFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # MiniGameMissionExcel
    def MissionRewardParcelTypeFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MiniGameMissionExcel
    def MissionRewardParcelTypeFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        return o == 0

    # MiniGameMissionExcel
    def MissionRewardParcelIdField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MiniGameMissionExcel
    def MissionRewardParcelIdFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # MiniGameMissionExcel
    def MissionRewardParcelIdFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MiniGameMissionExcel
    def MissionRewardParcelIdFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        return o == 0

    # MiniGameMissionExcel
    def MissionRewardAmountField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MiniGameMissionExcel
    def MissionRewardAmountFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # MiniGameMissionExcel
    def MissionRewardAmountFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MiniGameMissionExcel
    def MissionRewardAmountFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        return o == 0

    # MiniGameMissionExcel
    def ConditionRewardParcelTypeField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MiniGameMissionExcel
    def ConditionRewardParcelTypeFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # MiniGameMissionExcel
    def ConditionRewardParcelTypeFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MiniGameMissionExcel
    def ConditionRewardParcelTypeFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        return o == 0

    # MiniGameMissionExcel
    def ConditionRewardParcelIdField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MiniGameMissionExcel
    def ConditionRewardParcelIdFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # MiniGameMissionExcel
    def ConditionRewardParcelIdFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MiniGameMissionExcel
    def ConditionRewardParcelIdFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        return o == 0

    # MiniGameMissionExcel
    def ConditionRewardAmountField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MiniGameMissionExcel
    def ConditionRewardAmountFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # MiniGameMissionExcel
    def ConditionRewardAmountFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MiniGameMissionExcel
    def ConditionRewardAmountFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        return o == 0

def MiniGameMissionExcelStart(builder): builder.StartObject(29)
def Start(builder):
    return MiniGameMissionExcelStart(builder)
def MiniGameMissionExcelAddIdField(builder, idField): builder.PrependInt32Slot(0, idField, 0)
def AddIdField(builder, idField):
    return MiniGameMissionExcelAddIdField(builder, idField)
def MiniGameMissionExcelAddEventContentIdField(builder, eventContentIdField): builder.PrependInt32Slot(1, eventContentIdField, 0)
def AddEventContentIdField(builder, eventContentIdField):
    return MiniGameMissionExcelAddEventContentIdField(builder, eventContentIdField)
def MiniGameMissionExcelAddGroupIdField(builder, groupIdField): builder.PrependInt32Slot(2, groupIdField, 0)
def AddGroupIdField(builder, groupIdField):
    return MiniGameMissionExcelAddGroupIdField(builder, groupIdField)
def MiniGameMissionExcelAddGroupNameField(builder, groupNameField): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(groupNameField), 0)
def AddGroupNameField(builder, groupNameField):
    return MiniGameMissionExcelAddGroupNameField(builder, groupNameField)
def MiniGameMissionExcelAddCategoryField(builder, categoryField): builder.PrependInt32Slot(4, categoryField, 0)
def AddCategoryField(builder, categoryField):
    return MiniGameMissionExcelAddCategoryField(builder, categoryField)
def MiniGameMissionExcelAddDescriptionField(builder, descriptionField): builder.PrependUint32Slot(5, descriptionField, 0)
def AddDescriptionField(builder, descriptionField):
    return MiniGameMissionExcelAddDescriptionField(builder, descriptionField)
def MiniGameMissionExcelAddResetTypeField(builder, resetTypeField): builder.PrependInt32Slot(6, resetTypeField, 0)
def AddResetTypeField(builder, resetTypeField):
    return MiniGameMissionExcelAddResetTypeField(builder, resetTypeField)
def MiniGameMissionExcelAddToastDisplayTypeField(builder, toastDisplayTypeField): builder.PrependInt32Slot(7, toastDisplayTypeField, 0)
def AddToastDisplayTypeField(builder, toastDisplayTypeField):
    return MiniGameMissionExcelAddToastDisplayTypeField(builder, toastDisplayTypeField)
def MiniGameMissionExcelAddToastImagePathField(builder, toastImagePathField): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(toastImagePathField), 0)
def AddToastImagePathField(builder, toastImagePathField):
    return MiniGameMissionExcelAddToastImagePathField(builder, toastImagePathField)
def MiniGameMissionExcelAddViewFlagField(builder, viewFlagField): builder.PrependBoolSlot(9, viewFlagField, 0)
def AddViewFlagField(builder, viewFlagField):
    return MiniGameMissionExcelAddViewFlagField(builder, viewFlagField)
def MiniGameMissionExcelAddDisplayOrderField(builder, displayOrderField): builder.PrependInt32Slot(10, displayOrderField, 0)
def AddDisplayOrderField(builder, displayOrderField):
    return MiniGameMissionExcelAddDisplayOrderField(builder, displayOrderField)
def MiniGameMissionExcelAddPreMissionIdField(builder, preMissionIdField): builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(preMissionIdField), 0)
def AddPreMissionIdField(builder, preMissionIdField):
    return MiniGameMissionExcelAddPreMissionIdField(builder, preMissionIdField)
def MiniGameMissionExcelStartPreMissionIdFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartPreMissionIdFieldVector(builder, numElems):
    return MiniGameMissionExcelStartPreMissionIdFieldVector(builder, numElems)
def MiniGameMissionExcelAddTargetGroupField(builder, targetGroupField): builder.PrependInt32Slot(12, targetGroupField, 0)
def AddTargetGroupField(builder, targetGroupField):
    return MiniGameMissionExcelAddTargetGroupField(builder, targetGroupField)
def MiniGameMissionExcelAddAccountLevelField(builder, accountLevelField): builder.PrependInt32Slot(13, accountLevelField, 0)
def AddAccountLevelField(builder, accountLevelField):
    return MiniGameMissionExcelAddAccountLevelField(builder, accountLevelField)
def MiniGameMissionExcelAddShortcutUIField(builder, shortcutUIField): builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(shortcutUIField), 0)
def AddShortcutUIField(builder, shortcutUIField):
    return MiniGameMissionExcelAddShortcutUIField(builder, shortcutUIField)
def MiniGameMissionExcelStartShortcutUIFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartShortcutUIFieldVector(builder, numElems):
    return MiniGameMissionExcelStartShortcutUIFieldVector(builder, numElems)
def MiniGameMissionExcelAddCompleteConditionTypeField(builder, completeConditionTypeField): builder.PrependInt32Slot(15, completeConditionTypeField, 0)
def AddCompleteConditionTypeField(builder, completeConditionTypeField):
    return MiniGameMissionExcelAddCompleteConditionTypeField(builder, completeConditionTypeField)
def MiniGameMissionExcelAddIsCompleteExtensionTimeField(builder, isCompleteExtensionTimeField): builder.PrependBoolSlot(16, isCompleteExtensionTimeField, 0)
def AddIsCompleteExtensionTimeField(builder, isCompleteExtensionTimeField):
    return MiniGameMissionExcelAddIsCompleteExtensionTimeField(builder, isCompleteExtensionTimeField)
def MiniGameMissionExcelAddCompleteConditionCountField(builder, completeConditionCountField): builder.PrependInt32Slot(17, completeConditionCountField, 0)
def AddCompleteConditionCountField(builder, completeConditionCountField):
    return MiniGameMissionExcelAddCompleteConditionCountField(builder, completeConditionCountField)
def MiniGameMissionExcelAddCompleteConditionParameterField(builder, completeConditionParameterField): builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(completeConditionParameterField), 0)
def AddCompleteConditionParameterField(builder, completeConditionParameterField):
    return MiniGameMissionExcelAddCompleteConditionParameterField(builder, completeConditionParameterField)
def MiniGameMissionExcelStartCompleteConditionParameterFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartCompleteConditionParameterFieldVector(builder, numElems):
    return MiniGameMissionExcelStartCompleteConditionParameterFieldVector(builder, numElems)
def MiniGameMissionExcelAddCompleteConditionParameterTagField(builder, completeConditionParameterTagField): builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(completeConditionParameterTagField), 0)
def AddCompleteConditionParameterTagField(builder, completeConditionParameterTagField):
    return MiniGameMissionExcelAddCompleteConditionParameterTagField(builder, completeConditionParameterTagField)
def MiniGameMissionExcelStartCompleteConditionParameterTagFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartCompleteConditionParameterTagFieldVector(builder, numElems):
    return MiniGameMissionExcelStartCompleteConditionParameterTagFieldVector(builder, numElems)
def MiniGameMissionExcelAddRewardIconField(builder, rewardIconField): builder.PrependUOffsetTRelativeSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(rewardIconField), 0)
def AddRewardIconField(builder, rewardIconField):
    return MiniGameMissionExcelAddRewardIconField(builder, rewardIconField)
def MiniGameMissionExcelAddCompleteConditionMissionIdField(builder, completeConditionMissionIdField): builder.PrependUOffsetTRelativeSlot(21, flatbuffers.number_types.UOffsetTFlags.py_type(completeConditionMissionIdField), 0)
def AddCompleteConditionMissionIdField(builder, completeConditionMissionIdField):
    return MiniGameMissionExcelAddCompleteConditionMissionIdField(builder, completeConditionMissionIdField)
def MiniGameMissionExcelStartCompleteConditionMissionIdFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartCompleteConditionMissionIdFieldVector(builder, numElems):
    return MiniGameMissionExcelStartCompleteConditionMissionIdFieldVector(builder, numElems)
def MiniGameMissionExcelAddCompleteConditionMissionCountField(builder, completeConditionMissionCountField): builder.PrependInt32Slot(22, completeConditionMissionCountField, 0)
def AddCompleteConditionMissionCountField(builder, completeConditionMissionCountField):
    return MiniGameMissionExcelAddCompleteConditionMissionCountField(builder, completeConditionMissionCountField)
def MiniGameMissionExcelAddMissionRewardParcelTypeField(builder, missionRewardParcelTypeField): builder.PrependUOffsetTRelativeSlot(23, flatbuffers.number_types.UOffsetTFlags.py_type(missionRewardParcelTypeField), 0)
def AddMissionRewardParcelTypeField(builder, missionRewardParcelTypeField):
    return MiniGameMissionExcelAddMissionRewardParcelTypeField(builder, missionRewardParcelTypeField)
def MiniGameMissionExcelStartMissionRewardParcelTypeFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartMissionRewardParcelTypeFieldVector(builder, numElems):
    return MiniGameMissionExcelStartMissionRewardParcelTypeFieldVector(builder, numElems)
def MiniGameMissionExcelAddMissionRewardParcelIdField(builder, missionRewardParcelIdField): builder.PrependUOffsetTRelativeSlot(24, flatbuffers.number_types.UOffsetTFlags.py_type(missionRewardParcelIdField), 0)
def AddMissionRewardParcelIdField(builder, missionRewardParcelIdField):
    return MiniGameMissionExcelAddMissionRewardParcelIdField(builder, missionRewardParcelIdField)
def MiniGameMissionExcelStartMissionRewardParcelIdFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartMissionRewardParcelIdFieldVector(builder, numElems):
    return MiniGameMissionExcelStartMissionRewardParcelIdFieldVector(builder, numElems)
def MiniGameMissionExcelAddMissionRewardAmountField(builder, missionRewardAmountField): builder.PrependUOffsetTRelativeSlot(25, flatbuffers.number_types.UOffsetTFlags.py_type(missionRewardAmountField), 0)
def AddMissionRewardAmountField(builder, missionRewardAmountField):
    return MiniGameMissionExcelAddMissionRewardAmountField(builder, missionRewardAmountField)
def MiniGameMissionExcelStartMissionRewardAmountFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartMissionRewardAmountFieldVector(builder, numElems):
    return MiniGameMissionExcelStartMissionRewardAmountFieldVector(builder, numElems)
def MiniGameMissionExcelAddConditionRewardParcelTypeField(builder, conditionRewardParcelTypeField): builder.PrependUOffsetTRelativeSlot(26, flatbuffers.number_types.UOffsetTFlags.py_type(conditionRewardParcelTypeField), 0)
def AddConditionRewardParcelTypeField(builder, conditionRewardParcelTypeField):
    return MiniGameMissionExcelAddConditionRewardParcelTypeField(builder, conditionRewardParcelTypeField)
def MiniGameMissionExcelStartConditionRewardParcelTypeFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartConditionRewardParcelTypeFieldVector(builder, numElems):
    return MiniGameMissionExcelStartConditionRewardParcelTypeFieldVector(builder, numElems)
def MiniGameMissionExcelAddConditionRewardParcelIdField(builder, conditionRewardParcelIdField): builder.PrependUOffsetTRelativeSlot(27, flatbuffers.number_types.UOffsetTFlags.py_type(conditionRewardParcelIdField), 0)
def AddConditionRewardParcelIdField(builder, conditionRewardParcelIdField):
    return MiniGameMissionExcelAddConditionRewardParcelIdField(builder, conditionRewardParcelIdField)
def MiniGameMissionExcelStartConditionRewardParcelIdFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartConditionRewardParcelIdFieldVector(builder, numElems):
    return MiniGameMissionExcelStartConditionRewardParcelIdFieldVector(builder, numElems)
def MiniGameMissionExcelAddConditionRewardAmountField(builder, conditionRewardAmountField): builder.PrependUOffsetTRelativeSlot(28, flatbuffers.number_types.UOffsetTFlags.py_type(conditionRewardAmountField), 0)
def AddConditionRewardAmountField(builder, conditionRewardAmountField):
    return MiniGameMissionExcelAddConditionRewardAmountField(builder, conditionRewardAmountField)
def MiniGameMissionExcelStartConditionRewardAmountFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartConditionRewardAmountFieldVector(builder, numElems):
    return MiniGameMissionExcelStartConditionRewardAmountFieldVector(builder, numElems)
def MiniGameMissionExcelEnd(builder): return builder.EndObject()
def End(builder):
    return MiniGameMissionExcelEnd(builder)