# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MinigameJankenCharacterExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MinigameJankenCharacterExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMinigameJankenCharacterExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MinigameJankenCharacterExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MinigameJankenCharacterExcel
    def IdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameJankenCharacterExcel
    def IsPlayableField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MinigameJankenCharacterExcel
    def DisplayOrderField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameJankenCharacterExcel
    def IconResourceNameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameJankenCharacterExcel
    def IconDecoResourceNameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameJankenCharacterExcel
    def NameTagResourceNameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameJankenCharacterExcel
    def BattlePortraitResourceField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameJankenCharacterExcel
    def SkillIconResourceNameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameJankenCharacterExcel
    def SkillCardResourceNameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameJankenCharacterExcel
    def LocalizeIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MinigameJankenCharacterExcel
    def CharacterNameLocalizeIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MinigameJankenCharacterExcel
    def AttackPowerField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameJankenCharacterExcel
    def HitPointField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameJankenCharacterExcel
    def BlockPowerField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameJankenCharacterExcel
    def JankenSkillField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameJankenCharacterExcel
    def IsBossField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MinigameJankenCharacterExcel
    def IsBossUnitField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MinigameJankenCharacterExcel
    def ATGGaugeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameJankenCharacterExcel
    def ATGDmgBlockField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # MinigameJankenCharacterExcel
    def ATGDmgHitField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # MinigameJankenCharacterExcel
    def ATGLogicEffectField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MinigameJankenCharacterExcel
    def ModelPrefabNameField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MinigameJankenCharacterExcel
    def AiProfileField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def MinigameJankenCharacterExcelStart(builder): builder.StartObject(23)
def Start(builder):
    return MinigameJankenCharacterExcelStart(builder)
def MinigameJankenCharacterExcelAddIdField(builder, idField): builder.PrependInt32Slot(0, idField, 0)
def AddIdField(builder, idField):
    return MinigameJankenCharacterExcelAddIdField(builder, idField)
def MinigameJankenCharacterExcelAddIsPlayableField(builder, isPlayableField): builder.PrependBoolSlot(1, isPlayableField, 0)
def AddIsPlayableField(builder, isPlayableField):
    return MinigameJankenCharacterExcelAddIsPlayableField(builder, isPlayableField)
def MinigameJankenCharacterExcelAddDisplayOrderField(builder, displayOrderField): builder.PrependInt32Slot(2, displayOrderField, 0)
def AddDisplayOrderField(builder, displayOrderField):
    return MinigameJankenCharacterExcelAddDisplayOrderField(builder, displayOrderField)
def MinigameJankenCharacterExcelAddIconResourceNameField(builder, iconResourceNameField): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(iconResourceNameField), 0)
def AddIconResourceNameField(builder, iconResourceNameField):
    return MinigameJankenCharacterExcelAddIconResourceNameField(builder, iconResourceNameField)
def MinigameJankenCharacterExcelAddIconDecoResourceNameField(builder, iconDecoResourceNameField): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(iconDecoResourceNameField), 0)
def AddIconDecoResourceNameField(builder, iconDecoResourceNameField):
    return MinigameJankenCharacterExcelAddIconDecoResourceNameField(builder, iconDecoResourceNameField)
def MinigameJankenCharacterExcelAddNameTagResourceNameField(builder, nameTagResourceNameField): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(nameTagResourceNameField), 0)
def AddNameTagResourceNameField(builder, nameTagResourceNameField):
    return MinigameJankenCharacterExcelAddNameTagResourceNameField(builder, nameTagResourceNameField)
def MinigameJankenCharacterExcelAddBattlePortraitResourceField(builder, battlePortraitResourceField): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(battlePortraitResourceField), 0)
def AddBattlePortraitResourceField(builder, battlePortraitResourceField):
    return MinigameJankenCharacterExcelAddBattlePortraitResourceField(builder, battlePortraitResourceField)
def MinigameJankenCharacterExcelAddSkillIconResourceNameField(builder, skillIconResourceNameField): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(skillIconResourceNameField), 0)
def AddSkillIconResourceNameField(builder, skillIconResourceNameField):
    return MinigameJankenCharacterExcelAddSkillIconResourceNameField(builder, skillIconResourceNameField)
def MinigameJankenCharacterExcelAddSkillCardResourceNameField(builder, skillCardResourceNameField): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(skillCardResourceNameField), 0)
def AddSkillCardResourceNameField(builder, skillCardResourceNameField):
    return MinigameJankenCharacterExcelAddSkillCardResourceNameField(builder, skillCardResourceNameField)
def MinigameJankenCharacterExcelAddLocalizeIdField(builder, localizeIdField): builder.PrependUint32Slot(9, localizeIdField, 0)
def AddLocalizeIdField(builder, localizeIdField):
    return MinigameJankenCharacterExcelAddLocalizeIdField(builder, localizeIdField)
def MinigameJankenCharacterExcelAddCharacterNameLocalizeIdField(builder, characterNameLocalizeIdField): builder.PrependUint32Slot(10, characterNameLocalizeIdField, 0)
def AddCharacterNameLocalizeIdField(builder, characterNameLocalizeIdField):
    return MinigameJankenCharacterExcelAddCharacterNameLocalizeIdField(builder, characterNameLocalizeIdField)
def MinigameJankenCharacterExcelAddAttackPowerField(builder, attackPowerField): builder.PrependInt32Slot(11, attackPowerField, 0)
def AddAttackPowerField(builder, attackPowerField):
    return MinigameJankenCharacterExcelAddAttackPowerField(builder, attackPowerField)
def MinigameJankenCharacterExcelAddHitPointField(builder, hitPointField): builder.PrependInt32Slot(12, hitPointField, 0)
def AddHitPointField(builder, hitPointField):
    return MinigameJankenCharacterExcelAddHitPointField(builder, hitPointField)
def MinigameJankenCharacterExcelAddBlockPowerField(builder, blockPowerField): builder.PrependInt32Slot(13, blockPowerField, 0)
def AddBlockPowerField(builder, blockPowerField):
    return MinigameJankenCharacterExcelAddBlockPowerField(builder, blockPowerField)
def MinigameJankenCharacterExcelAddJankenSkillField(builder, jankenSkillField): builder.PrependInt32Slot(14, jankenSkillField, 0)
def AddJankenSkillField(builder, jankenSkillField):
    return MinigameJankenCharacterExcelAddJankenSkillField(builder, jankenSkillField)
def MinigameJankenCharacterExcelAddIsBossField(builder, isBossField): builder.PrependBoolSlot(15, isBossField, 0)
def AddIsBossField(builder, isBossField):
    return MinigameJankenCharacterExcelAddIsBossField(builder, isBossField)
def MinigameJankenCharacterExcelAddIsBossUnitField(builder, isBossUnitField): builder.PrependBoolSlot(16, isBossUnitField, 0)
def AddIsBossUnitField(builder, isBossUnitField):
    return MinigameJankenCharacterExcelAddIsBossUnitField(builder, isBossUnitField)
def MinigameJankenCharacterExcelAddATGGaugeField(builder, aTGGaugeField): builder.PrependInt32Slot(17, aTGGaugeField, 0)
def AddATGGaugeField(builder, aTGGaugeField):
    return MinigameJankenCharacterExcelAddATGGaugeField(builder, aTGGaugeField)
def MinigameJankenCharacterExcelAddATGDmgBlockField(builder, aTGDmgBlockField): builder.PrependFloat32Slot(18, aTGDmgBlockField, 0.0)
def AddATGDmgBlockField(builder, aTGDmgBlockField):
    return MinigameJankenCharacterExcelAddATGDmgBlockField(builder, aTGDmgBlockField)
def MinigameJankenCharacterExcelAddATGDmgHitField(builder, aTGDmgHitField): builder.PrependFloat32Slot(19, aTGDmgHitField, 0.0)
def AddATGDmgHitField(builder, aTGDmgHitField):
    return MinigameJankenCharacterExcelAddATGDmgHitField(builder, aTGDmgHitField)
def MinigameJankenCharacterExcelAddATGLogicEffectField(builder, aTGLogicEffectField): builder.PrependInt32Slot(20, aTGLogicEffectField, 0)
def AddATGLogicEffectField(builder, aTGLogicEffectField):
    return MinigameJankenCharacterExcelAddATGLogicEffectField(builder, aTGLogicEffectField)
def MinigameJankenCharacterExcelAddModelPrefabNameField(builder, modelPrefabNameField): builder.PrependUOffsetTRelativeSlot(21, flatbuffers.number_types.UOffsetTFlags.py_type(modelPrefabNameField), 0)
def AddModelPrefabNameField(builder, modelPrefabNameField):
    return MinigameJankenCharacterExcelAddModelPrefabNameField(builder, modelPrefabNameField)
def MinigameJankenCharacterExcelAddAiProfileField(builder, aiProfileField): builder.PrependInt32Slot(22, aiProfileField, 0)
def AddAiProfileField(builder, aiProfileField):
    return MinigameJankenCharacterExcelAddAiProfileField(builder, aiProfileField)
def MinigameJankenCharacterExcelEnd(builder): return builder.EndObject()
def End(builder):
    return MinigameJankenCharacterExcelEnd(builder)