# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PresetParcelsExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PresetParcelsExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPresetParcelsExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PresetParcelsExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PresetParcelsExcel
    def ParcelTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # PresetParcelsExcel
    def ParcelIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # PresetParcelsExcel
    def PresetGroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # PresetParcelsExcel
    def ParcelAmountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def PresetParcelsExcelStart(builder): builder.StartObject(4)
def Start(builder):
    return PresetParcelsExcelStart(builder)
def PresetParcelsExcelAddParcelTypeField(builder, parcelTypeField): builder.PrependInt32Slot(0, parcelTypeField, 0)
def AddParcelTypeField(builder, parcelTypeField):
    return PresetParcelsExcelAddParcelTypeField(builder, parcelTypeField)
def PresetParcelsExcelAddParcelIdField(builder, parcelIdField): builder.PrependInt32Slot(1, parcelIdField, 0)
def AddParcelIdField(builder, parcelIdField):
    return PresetParcelsExcelAddParcelIdField(builder, parcelIdField)
def PresetParcelsExcelAddPresetGroupIdField(builder, presetGroupIdField): builder.PrependInt32Slot(2, presetGroupIdField, 0)
def AddPresetGroupIdField(builder, presetGroupIdField):
    return PresetParcelsExcelAddPresetGroupIdField(builder, presetGroupIdField)
def PresetParcelsExcelAddParcelAmountField(builder, parcelAmountField): builder.PrependInt32Slot(3, parcelAmountField, 0)
def AddParcelAmountField(builder, parcelAmountField):
    return PresetParcelsExcelAddParcelAmountField(builder, parcelAmountField)
def PresetParcelsExcelEnd(builder): return builder.EndObject()
def End(builder):
    return PresetParcelsExcelEnd(builder)