# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ProductStreakRecordExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProductStreakRecordExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProductStreakRecordExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProductStreakRecordExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProductStreakRecordExcel
    def IdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ProductStreakRecordExcel
    def ProductIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ProductStreakRecordExcel
    def StoreTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ProductStreakRecordExcel
    def PriceField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ProductStreakRecordExcel
    def PurchaseCountLimitField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ProductStreakRecordExcel
    def StreakRecordIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ProductStreakRecordExcelStart(builder): builder.StartObject(6)
def Start(builder):
    return ProductStreakRecordExcelStart(builder)
def ProductStreakRecordExcelAddIdField(builder, idField): builder.PrependInt32Slot(0, idField, 0)
def AddIdField(builder, idField):
    return ProductStreakRecordExcelAddIdField(builder, idField)
def ProductStreakRecordExcelAddProductIdField(builder, productIdField): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(productIdField), 0)
def AddProductIdField(builder, productIdField):
    return ProductStreakRecordExcelAddProductIdField(builder, productIdField)
def ProductStreakRecordExcelAddStoreTypeField(builder, storeTypeField): builder.PrependInt32Slot(2, storeTypeField, 0)
def AddStoreTypeField(builder, storeTypeField):
    return ProductStreakRecordExcelAddStoreTypeField(builder, storeTypeField)
def ProductStreakRecordExcelAddPriceField(builder, priceField): builder.PrependInt32Slot(3, priceField, 0)
def AddPriceField(builder, priceField):
    return ProductStreakRecordExcelAddPriceField(builder, priceField)
def ProductStreakRecordExcelAddPurchaseCountLimitField(builder, purchaseCountLimitField): builder.PrependInt32Slot(4, purchaseCountLimitField, 0)
def AddPurchaseCountLimitField(builder, purchaseCountLimitField):
    return ProductStreakRecordExcelAddPurchaseCountLimitField(builder, purchaseCountLimitField)
def ProductStreakRecordExcelAddStreakRecordIdField(builder, streakRecordIdField): builder.PrependInt32Slot(5, streakRecordIdField, 0)
def AddStreakRecordIdField(builder, streakRecordIdField):
    return ProductStreakRecordExcelAddStreakRecordIdField(builder, streakRecordIdField)
def ProductStreakRecordExcelEnd(builder): return builder.EndObject()
def End(builder):
    return ProductStreakRecordExcelEnd(builder)