# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RaidSkillDescriptionListExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RaidSkillDescriptionListExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRaidSkillDescriptionListExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RaidSkillDescriptionListExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RaidSkillDescriptionListExcel
    def BossGroupField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RaidSkillDescriptionListExcel
    def DifficultyField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RaidSkillDescriptionListExcel
    def PhaseNameOverrideKeyField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RaidSkillDescriptionListExcel
    def SkillGroupIdField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # RaidSkillDescriptionListExcel
    def SkillGroupIdFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RaidSkillDescriptionListExcel
    def SkillGroupIdFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # RaidSkillDescriptionListExcel
    def SkillUsePhaseField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # RaidSkillDescriptionListExcel
    def SkillUsePhaseFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # RaidSkillDescriptionListExcel
    def SkillUsePhaseFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RaidSkillDescriptionListExcel
    def SkillUsePhaseFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # RaidSkillDescriptionListExcel
    def ShowSkillSlotField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # RaidSkillDescriptionListExcel
    def ShowSkillSlotFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # RaidSkillDescriptionListExcel
    def ShowSkillSlotFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RaidSkillDescriptionListExcel
    def ShowSkillSlotFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # RaidSkillDescriptionListExcel
    def HighlightResourceField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # RaidSkillDescriptionListExcel
    def HighlightResourceFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # RaidSkillDescriptionListExcel
    def HighlightResourceFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RaidSkillDescriptionListExcel
    def HighlightResourceFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def RaidSkillDescriptionListExcelStart(builder): builder.StartObject(7)
def Start(builder):
    return RaidSkillDescriptionListExcelStart(builder)
def RaidSkillDescriptionListExcelAddBossGroupField(builder, bossGroupField): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(bossGroupField), 0)
def AddBossGroupField(builder, bossGroupField):
    return RaidSkillDescriptionListExcelAddBossGroupField(builder, bossGroupField)
def RaidSkillDescriptionListExcelAddDifficultyField(builder, difficultyField): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(difficultyField), 0)
def AddDifficultyField(builder, difficultyField):
    return RaidSkillDescriptionListExcelAddDifficultyField(builder, difficultyField)
def RaidSkillDescriptionListExcelAddPhaseNameOverrideKeyField(builder, phaseNameOverrideKeyField): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(phaseNameOverrideKeyField), 0)
def AddPhaseNameOverrideKeyField(builder, phaseNameOverrideKeyField):
    return RaidSkillDescriptionListExcelAddPhaseNameOverrideKeyField(builder, phaseNameOverrideKeyField)
def RaidSkillDescriptionListExcelAddSkillGroupIdField(builder, skillGroupIdField): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(skillGroupIdField), 0)
def AddSkillGroupIdField(builder, skillGroupIdField):
    return RaidSkillDescriptionListExcelAddSkillGroupIdField(builder, skillGroupIdField)
def RaidSkillDescriptionListExcelStartSkillGroupIdFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartSkillGroupIdFieldVector(builder, numElems):
    return RaidSkillDescriptionListExcelStartSkillGroupIdFieldVector(builder, numElems)
def RaidSkillDescriptionListExcelAddSkillUsePhaseField(builder, skillUsePhaseField): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(skillUsePhaseField), 0)
def AddSkillUsePhaseField(builder, skillUsePhaseField):
    return RaidSkillDescriptionListExcelAddSkillUsePhaseField(builder, skillUsePhaseField)
def RaidSkillDescriptionListExcelStartSkillUsePhaseFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartSkillUsePhaseFieldVector(builder, numElems):
    return RaidSkillDescriptionListExcelStartSkillUsePhaseFieldVector(builder, numElems)
def RaidSkillDescriptionListExcelAddShowSkillSlotField(builder, showSkillSlotField): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(showSkillSlotField), 0)
def AddShowSkillSlotField(builder, showSkillSlotField):
    return RaidSkillDescriptionListExcelAddShowSkillSlotField(builder, showSkillSlotField)
def RaidSkillDescriptionListExcelStartShowSkillSlotFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartShowSkillSlotFieldVector(builder, numElems):
    return RaidSkillDescriptionListExcelStartShowSkillSlotFieldVector(builder, numElems)
def RaidSkillDescriptionListExcelAddHighlightResourceField(builder, highlightResourceField): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(highlightResourceField), 0)
def AddHighlightResourceField(builder, highlightResourceField):
    return RaidSkillDescriptionListExcelAddHighlightResourceField(builder, highlightResourceField)
def RaidSkillDescriptionListExcelStartHighlightResourceFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartHighlightResourceFieldVector(builder, numElems):
    return RaidSkillDescriptionListExcelStartHighlightResourceFieldVector(builder, numElems)
def RaidSkillDescriptionListExcelEnd(builder): return builder.EndObject()
def End(builder):
    return RaidSkillDescriptionListExcelEnd(builder)