# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SchoolDungeonRewardExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SchoolDungeonRewardExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSchoolDungeonRewardExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SchoolDungeonRewardExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SchoolDungeonRewardExcel
    def GroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SchoolDungeonRewardExcel
    def DungeonTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SchoolDungeonRewardExcel
    def RewardTagField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SchoolDungeonRewardExcel
    def RewardParcelTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SchoolDungeonRewardExcel
    def RewardParcelIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SchoolDungeonRewardExcel
    def RewardParcelAmountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SchoolDungeonRewardExcel
    def RewardParcelProbabilityField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SchoolDungeonRewardExcel
    def IsDisplayedField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SchoolDungeonRewardExcelStart(builder): builder.StartObject(8)
def Start(builder):
    return SchoolDungeonRewardExcelStart(builder)
def SchoolDungeonRewardExcelAddGroupIdField(builder, groupIdField): builder.PrependInt32Slot(0, groupIdField, 0)
def AddGroupIdField(builder, groupIdField):
    return SchoolDungeonRewardExcelAddGroupIdField(builder, groupIdField)
def SchoolDungeonRewardExcelAddDungeonTypeField(builder, dungeonTypeField): builder.PrependInt32Slot(1, dungeonTypeField, 0)
def AddDungeonTypeField(builder, dungeonTypeField):
    return SchoolDungeonRewardExcelAddDungeonTypeField(builder, dungeonTypeField)
def SchoolDungeonRewardExcelAddRewardTagField(builder, rewardTagField): builder.PrependFloat32Slot(2, rewardTagField, 0.0)
def AddRewardTagField(builder, rewardTagField):
    return SchoolDungeonRewardExcelAddRewardTagField(builder, rewardTagField)
def SchoolDungeonRewardExcelAddRewardParcelTypeField(builder, rewardParcelTypeField): builder.PrependInt32Slot(3, rewardParcelTypeField, 0)
def AddRewardParcelTypeField(builder, rewardParcelTypeField):
    return SchoolDungeonRewardExcelAddRewardParcelTypeField(builder, rewardParcelTypeField)
def SchoolDungeonRewardExcelAddRewardParcelIdField(builder, rewardParcelIdField): builder.PrependInt32Slot(4, rewardParcelIdField, 0)
def AddRewardParcelIdField(builder, rewardParcelIdField):
    return SchoolDungeonRewardExcelAddRewardParcelIdField(builder, rewardParcelIdField)
def SchoolDungeonRewardExcelAddRewardParcelAmountField(builder, rewardParcelAmountField): builder.PrependInt32Slot(5, rewardParcelAmountField, 0)
def AddRewardParcelAmountField(builder, rewardParcelAmountField):
    return SchoolDungeonRewardExcelAddRewardParcelAmountField(builder, rewardParcelAmountField)
def SchoolDungeonRewardExcelAddRewardParcelProbabilityField(builder, rewardParcelProbabilityField): builder.PrependInt32Slot(6, rewardParcelProbabilityField, 0)
def AddRewardParcelProbabilityField(builder, rewardParcelProbabilityField):
    return SchoolDungeonRewardExcelAddRewardParcelProbabilityField(builder, rewardParcelProbabilityField)
def SchoolDungeonRewardExcelAddIsDisplayedField(builder, isDisplayedField): builder.PrependBoolSlot(7, isDisplayedField, 0)
def AddIsDisplayedField(builder, isDisplayedField):
    return SchoolDungeonRewardExcelAddIsDisplayedField(builder, isDisplayedField)
def SchoolDungeonRewardExcelEnd(builder): return builder.EndObject()
def End(builder):
    return SchoolDungeonRewardExcelEnd(builder)