# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StudentFrameExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StudentFrameExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStudentFrameExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StudentFrameExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StudentFrameExcel
    def IdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StudentFrameExcel
    def CategoryField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StudentFrameExcel
    def DisplayOrderField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StudentFrameExcel
    def LocalizeEtcIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # StudentFrameExcel
    def IconPathField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StudentFrameExcel
    def FrameImagePathField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StudentFrameExcel
    def BigFrameImagePathField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StudentFrameExcel
    def EmblemEffectPathField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StudentFrameExcel
    def DisplayTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StudentFrameExcel
    def DisplayStartDateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StudentFrameExcel
    def DisplayEndDateField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StudentFrameExcel
    def DislpayLevelField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StudentFrameExcel
    def CheckPassTypeField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StudentFrameExcel
    def FrameParameterField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # StudentFrameExcel
    def CheckPassCountField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def StudentFrameExcelStart(builder): builder.StartObject(15)
def Start(builder):
    return StudentFrameExcelStart(builder)
def StudentFrameExcelAddIdField(builder, idField): builder.PrependInt32Slot(0, idField, 0)
def AddIdField(builder, idField):
    return StudentFrameExcelAddIdField(builder, idField)
def StudentFrameExcelAddCategoryField(builder, categoryField): builder.PrependInt32Slot(1, categoryField, 0)
def AddCategoryField(builder, categoryField):
    return StudentFrameExcelAddCategoryField(builder, categoryField)
def StudentFrameExcelAddDisplayOrderField(builder, displayOrderField): builder.PrependInt32Slot(2, displayOrderField, 0)
def AddDisplayOrderField(builder, displayOrderField):
    return StudentFrameExcelAddDisplayOrderField(builder, displayOrderField)
def StudentFrameExcelAddLocalizeEtcIdField(builder, localizeEtcIdField): builder.PrependUint32Slot(3, localizeEtcIdField, 0)
def AddLocalizeEtcIdField(builder, localizeEtcIdField):
    return StudentFrameExcelAddLocalizeEtcIdField(builder, localizeEtcIdField)
def StudentFrameExcelAddIconPathField(builder, iconPathField): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(iconPathField), 0)
def AddIconPathField(builder, iconPathField):
    return StudentFrameExcelAddIconPathField(builder, iconPathField)
def StudentFrameExcelAddFrameImagePathField(builder, frameImagePathField): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(frameImagePathField), 0)
def AddFrameImagePathField(builder, frameImagePathField):
    return StudentFrameExcelAddFrameImagePathField(builder, frameImagePathField)
def StudentFrameExcelAddBigFrameImagePathField(builder, bigFrameImagePathField): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(bigFrameImagePathField), 0)
def AddBigFrameImagePathField(builder, bigFrameImagePathField):
    return StudentFrameExcelAddBigFrameImagePathField(builder, bigFrameImagePathField)
def StudentFrameExcelAddEmblemEffectPathField(builder, emblemEffectPathField): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(emblemEffectPathField), 0)
def AddEmblemEffectPathField(builder, emblemEffectPathField):
    return StudentFrameExcelAddEmblemEffectPathField(builder, emblemEffectPathField)
def StudentFrameExcelAddDisplayTypeField(builder, displayTypeField): builder.PrependInt32Slot(8, displayTypeField, 0)
def AddDisplayTypeField(builder, displayTypeField):
    return StudentFrameExcelAddDisplayTypeField(builder, displayTypeField)
def StudentFrameExcelAddDisplayStartDateField(builder, displayStartDateField): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(displayStartDateField), 0)
def AddDisplayStartDateField(builder, displayStartDateField):
    return StudentFrameExcelAddDisplayStartDateField(builder, displayStartDateField)
def StudentFrameExcelAddDisplayEndDateField(builder, displayEndDateField): builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(displayEndDateField), 0)
def AddDisplayEndDateField(builder, displayEndDateField):
    return StudentFrameExcelAddDisplayEndDateField(builder, displayEndDateField)
def StudentFrameExcelAddDislpayLevelField(builder, dislpayLevelField): builder.PrependInt32Slot(11, dislpayLevelField, 0)
def AddDislpayLevelField(builder, dislpayLevelField):
    return StudentFrameExcelAddDislpayLevelField(builder, dislpayLevelField)
def StudentFrameExcelAddCheckPassTypeField(builder, checkPassTypeField): builder.PrependInt32Slot(12, checkPassTypeField, 0)
def AddCheckPassTypeField(builder, checkPassTypeField):
    return StudentFrameExcelAddCheckPassTypeField(builder, checkPassTypeField)
def StudentFrameExcelAddFrameParameterField(builder, frameParameterField): builder.PrependInt32Slot(13, frameParameterField, 0)
def AddFrameParameterField(builder, frameParameterField):
    return StudentFrameExcelAddFrameParameterField(builder, frameParameterField)
def StudentFrameExcelAddCheckPassCountField(builder, checkPassCountField): builder.PrependInt32Slot(14, checkPassCountField, 0)
def AddCheckPassCountField(builder, checkPassCountField):
    return StudentFrameExcelAddCheckPassCountField(builder, checkPassCountField)
def StudentFrameExcelEnd(builder): return builder.EndObject()
def End(builder):
    return StudentFrameExcelEnd(builder)