# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TacticalRelayCharacterBanExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TacticalRelayCharacterBanExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTacticalRelayCharacterBanExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TacticalRelayCharacterBanExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TacticalRelayCharacterBanExcel
    def SeasonGroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TacticalRelayCharacterBanExcel
    def CharacterIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def TacticalRelayCharacterBanExcelStart(builder): builder.StartObject(2)
def Start(builder):
    return TacticalRelayCharacterBanExcelStart(builder)
def TacticalRelayCharacterBanExcelAddSeasonGroupIdField(builder, seasonGroupIdField): builder.PrependInt32Slot(0, seasonGroupIdField, 0)
def AddSeasonGroupIdField(builder, seasonGroupIdField):
    return TacticalRelayCharacterBanExcelAddSeasonGroupIdField(builder, seasonGroupIdField)
def TacticalRelayCharacterBanExcelAddCharacterIdField(builder, characterIdField): builder.PrependInt32Slot(1, characterIdField, 0)
def AddCharacterIdField(builder, characterIdField):
    return TacticalRelayCharacterBanExcelAddCharacterIdField(builder, characterIdField)
def TacticalRelayCharacterBanExcelEnd(builder): return builder.EndObject()
def End(builder):
    return TacticalRelayCharacterBanExcelEnd(builder)