# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TrophyCollectionExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrophyCollectionExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrophyCollectionExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrophyCollectionExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrophyCollectionExcel
    def GroupIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # TrophyCollectionExcel
    def LocalizeCodeIdField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # TrophyCollectionExcel
    def FurnitureIdField(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # TrophyCollectionExcel
    def FurnitureIdFieldAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # TrophyCollectionExcel
    def FurnitureIdFieldLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TrophyCollectionExcel
    def FurnitureIdFieldIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def TrophyCollectionExcelStart(builder): builder.StartObject(3)
def Start(builder):
    return TrophyCollectionExcelStart(builder)
def TrophyCollectionExcelAddGroupIdField(builder, groupIdField): builder.PrependInt32Slot(0, groupIdField, 0)
def AddGroupIdField(builder, groupIdField):
    return TrophyCollectionExcelAddGroupIdField(builder, groupIdField)
def TrophyCollectionExcelAddLocalizeCodeIdField(builder, localizeCodeIdField): builder.PrependUint32Slot(1, localizeCodeIdField, 0)
def AddLocalizeCodeIdField(builder, localizeCodeIdField):
    return TrophyCollectionExcelAddLocalizeCodeIdField(builder, localizeCodeIdField)
def TrophyCollectionExcelAddFurnitureIdField(builder, furnitureIdField): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(furnitureIdField), 0)
def AddFurnitureIdField(builder, furnitureIdField):
    return TrophyCollectionExcelAddFurnitureIdField(builder, furnitureIdField)
def TrophyCollectionExcelStartFurnitureIdFieldVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartFurnitureIdFieldVector(builder, numElems):
    return TrophyCollectionExcelStartFurnitureIdFieldVector(builder, numElems)
def TrophyCollectionExcelEnd(builder): return builder.EndObject()
def End(builder):
    return TrophyCollectionExcelEnd(builder)