# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VoiceRoomExceptionExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VoiceRoomExceptionExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVoiceRoomExceptionExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VoiceRoomExceptionExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VoiceRoomExceptionExcel
    def CostumeUniqueId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VoiceRoomExceptionExcel
    def LinkedCharacterVoicePrintType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # VoiceRoomExceptionExcel
    def LinkedCostumeUniqueId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def VoiceRoomExceptionExcelStart(builder): builder.StartObject(3)
def Start(builder):
    return VoiceRoomExceptionExcelStart(builder)
def VoiceRoomExceptionExcelAddCostumeUniqueId(builder, costumeUniqueId): builder.PrependInt32Slot(0, costumeUniqueId, 0)
def AddCostumeUniqueId(builder, costumeUniqueId):
    return VoiceRoomExceptionExcelAddCostumeUniqueId(builder, costumeUniqueId)
def VoiceRoomExceptionExcelAddLinkedCharacterVoicePrintType(builder, linkedCharacterVoicePrintType): builder.PrependInt32Slot(1, linkedCharacterVoicePrintType, 0)
def AddLinkedCharacterVoicePrintType(builder, linkedCharacterVoicePrintType):
    return VoiceRoomExceptionExcelAddLinkedCharacterVoicePrintType(builder, linkedCharacterVoicePrintType)
def VoiceRoomExceptionExcelAddLinkedCostumeUniqueId(builder, linkedCostumeUniqueId): builder.PrependInt32Slot(2, linkedCostumeUniqueId, 0)
def AddLinkedCostumeUniqueId(builder, linkedCostumeUniqueId):
    return VoiceRoomExceptionExcelAddLinkedCostumeUniqueId(builder, linkedCostumeUniqueId)
def VoiceRoomExceptionExcelEnd(builder): return builder.EndObject()
def End(builder):
    return VoiceRoomExceptionExcelEnd(builder)